project:
  type: book

book:
  title: "Labmanual General Biology II"
  subtitle: "BI104 | Spring 2024 | Saint Anselm College"
  author: "Shannon J O'Leary"
  date: today
  chapters:
    - index.qmd
    
    - part: A_Biomes.qmd
      chapters: 
        - A01_climate.qmd
        - A02_biomes.qmd

    
    - part: B_ecol-succession.qmd
      chapters:
        - B01_exp-design.qmd
        - B02_methods.qmd
        - B03_data-collection.qmd
        - B04_data-analysis.qmd
        
    
    - part: C_bioassays.qmd

    
    - part: D_lichens.qmd


    - part: E_tracking.qmd
      chapters:
        - E01_winter-ecol.qmd
        - E02_tracking.qmd
    
    - part: F_Exp-Design-Analysis.qmd


    - part: Z_Appendix.qmd
      chapters:
        - references.qmd

bibliography: references.bib

format:
  html:
    theme: sandstone
    toc: true
    toc-depth: 2
    toc-location: left
    code-fold: false
    code-overflow: scroll
    code-copy: hover
    number-sections: true
    anchor-sections: true
    embed-resources: true
  # pdf:
  #   documentclass: scrreprt

reference-location: margin
citation-location: margin
fig-cap-location: margin
tbl-cap-location: margin



