{
  "hash": "2b0f0a1ff6e32a787070a298e4f3f218",
  "result": {
    "markdown": "# Analyze your data\n\n\n\n\n\nAfter completing this set of activities, you should be able to:\n\n-   assess what information is contained in a data set.\n-   decide what type of descriptive statistics to apply according to whether a variable is continuous or categorical.\n-   distinguish between a null and alternative hypothesis and interpret the results of a statistical test for significant differences among means and frequencies.\n\nBefore we get started we will need to load our `R` libraries that contain the functions we will need to analyze our data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load libraries for reporting\nlibrary(knitr)\n\n# load libraries for data import\nlibrary(readr)\nlibrary(here)\nlibrary(janitor)\n\n# load libraries for data wrangling\nlibrary(dplyr)\nlibrary(tidyr)\nlibrary(broom)\n\n# load libraries for plotting\nlibrary(ggplot2)\n\n# load library for inferential stats\nlibrary(infer)\nlibrary(chisq.posthoc.test)\n```\n:::\n\n\n## Germination Data\n\n### Get the data\n\nGo to the `GoogleSheet` that contains the germination counts for your lab and select the tab for your group.\n\n-   Double check that the data has been entered correctly.\n-   Go to `File` -\\> `Download` -\\> `Comma Separated Values (.csv)` to download your data as a comma-delimited file.\n-   Use your `File Explorer` if you are on a Windows computer and `Finder` of you are on a Mac and navigate to the `Downloads` folder. You should see the file you just downloaded there.\n\nNow we have to upload the file to our posit cloud `R project`.\n\n-   In the `File` tab (lower right panel) navigate to the `data` folder.\n-   Select the `Uploads` button.\n-   Use the dialog box to select `Choose File` button and navigate to your file in the downloads folder.\n-   Select your file and upload it.\n-   Check the box next to the file you just uploaded it and use the `Rename` button to rename it to `germination.csv`.\n\nNow we are ready to read in our germination data as a `data.frame` object that we can compute on in `R`. We will create three objects, the first is a generated data set comparing the impacts of different deicers on mung beans, the second the data radish seed data sets from Section A and B.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# read in example data set\ngermination_ex <- read_delim(here(\"data\", \"germination-1.csv\"), delim = \",\") %>%\n  clean_names() %>%\n  unite(treatment, deicer, treatment_level,\n        sep = \"_\", remove = FALSE) %>%\n  mutate(treatment_level = factor(treatment_level, \n                                   levels = c(\"high\", \"medium\", \"low\", \"trace\")))\n\n# read in Section A data set\ngermination_A <- read_delim(here(\"data\", \"germination_Section-A.csv\"), delim = \",\") %>%\n  clean_names() %>%\n  unite(treatment, deicer, treatment_level,\n        sep = \"_\", remove = FALSE) %>%\n  mutate(treatment_level = factor(treatment_level, \n                                   levels = c(\"high\", \"medium\", \"low\", \"trace\")))\n\n# read in Section B data set\ngermination_B <- read_delim(here(\"data\", \"germination_Section-B.csv\"), delim = \",\") %>%\n  clean_names() %>%\n  unite(treatment, deicer, treatment_level,\n        sep = \"_\", remove = FALSE) %>%\n  mutate(treatment_level = factor(treatment_level, \n                                   levels = c(\"high\", \"medium\", \"low\", \"trace\")))\n\n# take a look at first few lines\nhead(germination_ex) %>%\n  kable()\n```\n\n::: {.cell-output-display}\n|treatment      |deicer    |treatment_level | concentration|units | replicate| seed_number|germination    |setup_date |observation_date |observation_time |initials |notes     |\n|:--------------|:---------|:---------------|-------------:|:-----|---------:|-----------:|:--------------|:----------|:----------------|:----------------|:--------|:---------|\n|rock_salt_high |rock_salt |high            |            10|mg/L  |         1|           1|no_germination |2025-03-01 |2025-03-02       |08:00:00         |JD       |No issues |\n|rock_salt_high |rock_salt |high            |            10|mg/L  |         1|           2|germinated     |2025-03-01 |2025-03-02       |08:00:00         |JD       |No issues |\n|rock_salt_high |rock_salt |high            |            10|mg/L  |         1|           3|no_germination |2025-03-01 |2025-03-02       |08:00:00         |JD       |No issues |\n|rock_salt_high |rock_salt |high            |            10|mg/L  |         1|           4|germinated     |2025-03-01 |2025-03-02       |08:00:00         |JD       |No issues |\n|rock_salt_high |rock_salt |high            |            10|mg/L  |         1|           5|no_germination |2025-03-01 |2025-03-02       |08:00:00         |JD       |No issues |\n|rock_salt_high |rock_salt |high            |            10|mg/L  |         1|           6|no_germination |2025-03-01 |2025-03-02       |08:00:00         |JD       |No issues |\n:::\n:::\n\n\n::: {.callout-tip title=\"Consider this\"}\nTake a look at the `data.frame` object holding your data by clicking on it in the `Environment` pane (bottom left) or using `View(object_name)`.\n\nDescribe how your data is organized:\n\n-   what information is in each row?\n-   what information is in each column?\n\nFind your explanatory (independent) and response (dependent) variables in the data set.\n\nAssess what type of data you have in each column:\n\n-   is it continuous or categorical?\n-   what groups are you interested in comparing?\n\nFinally, determine which summary/descriptive statistics are appropriate to summarize this data set and how you would visualize your data.\n:::\n\n::: {.callout-note title=\"Answer\" collapse=\"true\"}\nEach row represents one seed. And each column contains information for one variable.\n\nYour explanatory variables are the individual treatments, this is categorical data. Similarly, your response variable is the germination data which is categorical with two possible values \"germinated\" and \"not germinated\".\n\nWe want to know the total number of seeds that germinated and did not germinate across all replicates for each treatment, and what proportion of the total number of seeds germinated.\n\nBecause we have categorical data and want to visualize how the data is distributed across our categories, we will want to use a bar plot to visualize our data.\n:::\n\nWe've discussed the need to QA/QC data. Usually whenever we read in data sets it can be helpful to create a few overview tables that allow us to look at the different parameters that were recorded (should be organized in columns) and number of observations in various groupings. These tables can be useful for describing your experimental design as well as an overview of what your data set looked like for your results section.\n\nLet's start with our example data set:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# count number of observations per deicer\ngermination_ex %>%\n  group_by(deicer) %>%\n  count() %>%\n  kable()\n```\n\n::: {.cell-output-display}\n|deicer       |   n|\n|:------------|---:|\n|cheese_brine | 180|\n|comm_blend   | 180|\n|control      |  60|\n|rock_salt    | 180|\n:::\n:::\n\n\n::: {.callout-tip title=\"Give it a try\"}\nCreate a copy of the code and then modify it to produce a similar table that shows the number of observation per treatment and replicate.\n\nThen produce a version of each of the two tables for the other two data sets.\n:::\n\n::: {.callout-note title=\"Answer\" collapse=\"true\"}\nYou can choose any set of columns to group by (remember to not use quotation marks and separate them by a comma) as long as you type the column name in exactly:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# count number of observations per treatment and replicate\ngermination_ex %>%\n  group_by(treatment, replicate) %>%\n  count() %>%\n  kable()\n```\n\n::: {.cell-output-display}\n|treatment           | replicate|  n|\n|:-------------------|---------:|--:|\n|cheese_brine_high   |         1| 20|\n|cheese_brine_high   |         2| 20|\n|cheese_brine_high   |         3| 20|\n|cheese_brine_low    |         1| 20|\n|cheese_brine_low    |         2| 20|\n|cheese_brine_low    |         3| 20|\n|cheese_brine_medium |         1| 20|\n|cheese_brine_medium |         2| 20|\n|cheese_brine_medium |         3| 20|\n|comm_blend_high     |         1| 20|\n|comm_blend_high     |         2| 20|\n|comm_blend_high     |         3| 20|\n|comm_blend_low      |         1| 20|\n|comm_blend_low      |         2| 20|\n|comm_blend_low      |         3| 20|\n|comm_blend_medium   |         1| 20|\n|comm_blend_medium   |         2| 20|\n|comm_blend_medium   |         3| 20|\n|control_high        |         1| 20|\n|control_high        |         2| 20|\n|control_high        |         3| 20|\n|rock_salt_high      |         1| 20|\n|rock_salt_high      |         2| 20|\n|rock_salt_high      |         3| 20|\n|rock_salt_low       |         1| 20|\n|rock_salt_low       |         2| 20|\n|rock_salt_low       |         3| 20|\n|rock_salt_medium    |         1| 20|\n|rock_salt_medium    |         2| 20|\n|rock_salt_medium    |         3| 20|\n:::\n:::\n\n\nThen for the other tables you just have to change the object name in the first line.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# count number of observations per deicer\ngermination_A %>%\n  group_by(deicer) %>%\n  count() %>%\n  kable()\n```\n\n::: {.cell-output-display}\n|deicer     |   n|\n|:----------|---:|\n|Fusion2330 | 200|\n|NaCl       | 240|\n|control    |  60|\n:::\n\n```{.r .cell-code}\n# count number of observations per treatment and replicate\ngermination_A %>%\n  group_by(treatment, replicate) %>%\n  count() %>%\n  kable()\n```\n\n::: {.cell-output-display}\n|treatment         | replicate|  n|\n|:-----------------|---------:|--:|\n|Fusion2330_high   |         1| 20|\n|Fusion2330_high   |         2| 20|\n|Fusion2330_high   |         3| 20|\n|Fusion2330_low    |         1| 20|\n|Fusion2330_medium |         1| 20|\n|Fusion2330_medium |         2| 20|\n|Fusion2330_medium |         3| 20|\n|Fusion2330_trace  |         1| 20|\n|Fusion2330_trace  |         2| 20|\n|Fusion2330_trace  |         3| 20|\n|NaCl_high         |         1| 20|\n|NaCl_high         |         2| 20|\n|NaCl_high         |         3| 20|\n|NaCl_low          |         1| 20|\n|NaCl_low          |         2| 20|\n|NaCl_low          |         3| 20|\n|NaCl_medium       |         1| 20|\n|NaCl_medium       |         2| 20|\n|NaCl_medium       |         3| 20|\n|NaCl_trace        |         1| 20|\n|NaCl_trace        |         2| 20|\n|NaCl_trace        |         3| 20|\n|control_NA        |         1| 20|\n|control_NA        |         2| 20|\n|control_NA        |         3| 20|\n:::\n\n```{.r .cell-code}\n# count number of observations per treatment overall\ngermination_A %>%\n  group_by(treatment) %>%\n  count() %>%\n  kable()\n```\n\n::: {.cell-output-display}\n|treatment         |  n|\n|:-----------------|--:|\n|Fusion2330_high   | 60|\n|Fusion2330_low    | 20|\n|Fusion2330_medium | 60|\n|Fusion2330_trace  | 60|\n|NaCl_high         | 60|\n|NaCl_low          | 60|\n|NaCl_medium       | 60|\n|NaCl_trace        | 60|\n|control_NA        | 60|\n:::\n\n```{.r .cell-code}\n# count number of observations per deicer\ngermination_B %>%\n  group_by(deicer) %>%\n  count() %>%\n  kable()\n```\n\n::: {.cell-output-display}\n|deicer    |   n|\n|:---------|---:|\n|CaCl      |  99|\n|DI-water  |  60|\n|MgCl      | 101|\n|NaCl      |  60|\n|beet      | 120|\n|tap-water |  60|\n|urea      | 120|\n:::\n\n```{.r .cell-code}\n# count number of observations per treatment and replicate\ngermination_B %>%\n  group_by(treatment, replicate) %>%\n  count() %>%\n  kable()\n```\n\n::: {.cell-output-display}\n|treatment    | replicate|  n|\n|:------------|---------:|--:|\n|CaCl_high    |         1| 19|\n|CaCl_high    |         3| 20|\n|CaCl_low     |         1| 20|\n|CaCl_low     |         2| 20|\n|CaCl_low     |         3| 20|\n|DI-water_NA  |         1| 20|\n|DI-water_NA  |         2| 20|\n|DI-water_NA  |         3| 20|\n|MgCl_high    |         1| 22|\n|MgCl_high    |         2| 20|\n|MgCl_low     |         1| 21|\n|MgCl_low     |         2| 18|\n|MgCl_low     |         3| 20|\n|NaCl_high    |         1| 20|\n|NaCl_high    |         2| 20|\n|NaCl_high    |         3| 20|\n|beet_high    |         1| 20|\n|beet_high    |         2| 20|\n|beet_high    |         3| 20|\n|beet_low     |         1| 20|\n|beet_low     |         2| 20|\n|beet_low     |         3| 20|\n|tap-water_NA |         1| 20|\n|tap-water_NA |         2| 20|\n|tap-water_NA |         3| 20|\n|urea_high    |         1| 20|\n|urea_high    |         2| 20|\n|urea_high    |         3| 20|\n|urea_low     |         1| 20|\n|urea_low     |         2| 20|\n|urea_low     |         3| 20|\n:::\n\n```{.r .cell-code}\n# count number of observations per treatment overall\ngermination_B %>%\n  group_by(treatment) %>%\n  count() %>%\n  kable()\n```\n\n::: {.cell-output-display}\n|treatment    |  n|\n|:------------|--:|\n|CaCl_high    | 39|\n|CaCl_low     | 60|\n|DI-water_NA  | 60|\n|MgCl_high    | 42|\n|MgCl_low     | 59|\n|NaCl_high    | 60|\n|beet_high    | 60|\n|beet_low     | 60|\n|tap-water_NA | 60|\n|urea_high    | 60|\n|urea_low     | 60|\n:::\n:::\n\n\nWe can see from these overview tables that we have a few plates where we didn't get exactly 20 seeds in the petri dish. We also seem to have some treatments where a replicate or two is missing.\n:::\n\n### Summarize your results\n\nNow, we can actually start analyzing our results. First, we will want to identify ways to summarize our data so we can identify broad trends and compare the different treatments.\n\n::: {.callout-tip title=\"Consider this\"}\nYour `data.frame` contains the raw data.\n\nSuggest 2-3 ways that you can summarize your data in a meaningful way to describe your results in the context of the hypothesis you are exploring with this experiment. Explain why you think these would be appropriate data analysis methods.\n:::\n\n::: {.callout-note title=\"Answer\" collapse=\"true\"}\nWe are going to calculate the total number and relative proportion of seeds that germinated for each treatment.\n\nA good visualization would be a bar plot where the height of each bar on the y-axis indicate the proportion of seeds that germinated.\n:::\n\n\n::: {#tbl-germination-success-I .cell tbl-cap='Summary of germination success after 48 hrs. Total number (n) and percent of seeds that germinated.'}\n\n```{.r .cell-code}\n# tidy data set\ngermination_ex %>%\n  group_by(deicer, treatment_level) %>% # group data by treatment\n  count(germination) %>%                # count number seeds germinated\n  mutate(percent = n/sum(n)*100) %>%\n  filter(germination == \"germinated\") %>%\n  kable(digits = 2)\n```\n\n::: {.cell-output-display}\n|deicer       |treatment_level |germination |  n| percent|\n|:------------|:---------------|:-----------|--:|-------:|\n|cheese_brine |high            |germinated  | 39|   65.00|\n|cheese_brine |medium          |germinated  | 53|   88.33|\n|cheese_brine |low             |germinated  | 52|   86.67|\n|comm_blend   |high            |germinated  | 24|   40.00|\n|comm_blend   |medium          |germinated  | 36|   60.00|\n|comm_blend   |low             |germinated  | 50|   83.33|\n|control      |high            |germinated  | 55|   91.67|\n|rock_salt    |high            |germinated  | 11|   18.33|\n|rock_salt    |medium          |germinated  | 28|   46.67|\n|rock_salt    |low             |germinated  | 33|   55.00|\n:::\n:::\n\n\nThis table gives you two summary statistics, but the table might not be the best way to present your data for easy comparison in a report.\n\nAn easier way to compare would be to pivot our data set into a wider format:\n\n\n::: {#tbl-germination-success-II .cell tbl-cap='Summary of germination success after 48 hrs for each deicer and concentration. Total number (n) and percent of seeds that germinated.'}\n\n```{.r .cell-code}\n# wide table\ngermination_ex %>%\n  group_by(deicer, treatment_level) %>% # group data by treatment\n  count(germination) %>%                # count number seeds germinated\n  mutate(percent = n/sum(n)*100) %>%\n  select(-n) %>%\n  filter(germination == \"germinated\") %>%\n  pivot_wider(names_from = treatment_level, values_from = percent) %>%\n  kable(digits = 2)\n```\n\n::: {.cell-output-display}\n|deicer       |germination |  high| medium|   low|\n|:------------|:-----------|-----:|------:|-----:|\n|cheese_brine |germinated  | 65.00|  88.33| 86.67|\n|comm_blend   |germinated  | 40.00|  60.00| 83.33|\n|control      |germinated  | 91.67|     NA|    NA|\n|rock_salt    |germinated  | 18.33|  46.67| 55.00|\n:::\n:::\n\n\n::: {.callout-tip title=\"Give it a try\"}\nModify the code to create similar tables for your data sets.\n:::\n\n::: {.callout-note title=\"Answer\" collapse=\"true\"}\n\n::: {.cell}\n\n```{.r .cell-code}\n# wide table\ngermination_A %>%\n  group_by(deicer, treatment_level) %>% # group data by treatment\n  count(germination) %>%                # count number seeds germinated\n  mutate(percent = n/sum(n)*100) %>%\n  select(-n) %>%\n  filter(germination == \"germinated\") %>%\n  pivot_wider(names_from = treatment_level, values_from = percent) %>%\n  kable(digits = 2)\n```\n\n::: {.cell-output-display}\n|deicer     |germination |  high| medium| low| trace|    NA|\n|:----------|:-----------|-----:|------:|---:|-----:|-----:|\n|Fusion2330 |germinated  | 98.33|  95.00| 100| 88.33|    NA|\n|NaCl       |germinated  | 65.00|  96.67| 100| 98.33|    NA|\n|control    |germinated  |    NA|     NA|  NA|    NA| 98.33|\n:::\n\n```{.r .cell-code}\n# wide table\ngermination_B %>%\n  group_by(deicer, treatment_level) %>% # group data by treatment\n  count(germination) %>%                # count number seeds germinated\n  mutate(percent = n/sum(n)*100) %>%\n  select(-n) %>%\n  filter(germination == \"germinated\") %>%\n  pivot_wider(names_from = treatment_level, values_from = percent) %>%\n  kable(digits = 2)\n```\n\n::: {.cell-output-display}\n|deicer    |germination |   high|    low|     NA|\n|:---------|:-----------|------:|------:|------:|\n|CaCl      |germinated  |  82.05|  73.33|     NA|\n|DI-water  |germinated  |     NA|     NA| 100.00|\n|MgCl      |germinated  |  95.24|  98.31|     NA|\n|NaCl      |germinated  |  65.00|     NA|     NA|\n|beet      |germinated  | 100.00| 100.00|     NA|\n|tap-water |germinated  |     NA|     NA|  98.33|\n|urea      |germinated  | 100.00| 100.00|     NA|\n:::\n:::\n\n:::\n\nData visualizations are frequently more helpful present your results compared to tables with numbers, so let's create a grouped bar chart visualizing the proportion of seeds that did/did not germinate.\n\nWe'll start by comparing the proportion that germinated for each treatment.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create table with % germinated\nsummary <- germination_ex |>\n  group_by(deicer, treatment_level) |> # group data by treatment\n  count(germination) |>                # count number seeds germinated\n  mutate(percent = n/sum(n)*100)       # calculate proportion\n\n# subset data to show % not germinated ----\ngermination <- summary |>\n  filter(germination == \"germinated\")\n\n# create bar plot with frequency\nggplot(germination, aes(x = deicer,                  # specify categories on x axis\n                        y = percent,\n                        fill = treatment_level)) +   # specify how to group data\n  geom_bar(stat = \"identity\",                        # length of bar indicates number of observations\n           width = .75,                              # space between groups\n           position = position_dodge(.8, \n                                     preserve = \"single\"), # space between bars in group\n           color = \"black\") +                        # line color of bar\n  scale_fill_manual(values = c(\"#4E5283\", \n                               \"#7871AA\", \n                               \"#D9BBF9\",\n                               \"#AA9FB1\")) +      # modify for custom colors\n  labs(x = \"deicer type\",                    # x-axis title\n       y = \"% of seeds that did not germinate\") +                  # y-axis title\n  theme_classic() +                                  # specify theme\n  theme(legend.position = \"bottom\")                  # legend position \n```\n\n::: {.cell-output-display}\n![Comparison of germination success of mung beans exposed to different deicers and concentration levels (high = 10mg/L, medium = 1 mg/L, low = 0.1 mgl/L).](C04_analyze_files/figure-html/fig-germination-success-1.png){#fig-germination-success width=672}\n:::\n:::\n\n\n::: {.callout-tip title=\"Give it a try\"}\nModify the code to create a similar visualization for your data sets.\n:::\n\n::: {.callout-note title=\"Answer\" collapse=\"true\"}\n\n::: {.cell}\n\n```{.r .cell-code}\n# create table with % germinated\nsummary <- germination_A |>\n  group_by(deicer, treatment_level) |> # group data by treatment\n  count(germination) |>                # count number seeds germinated\n  mutate(percent = n/sum(n)*100)       # calculate proportion\n\n# subset data to show % not germinated ----\nno_germination <- summary |>\n  filter(germination == \"germinated\")\n\n# create bar plot with frequency\nggplot(no_germination, aes(x = deicer,                  # specify categories on x axis\n                        y = percent,\n                        fill = treatment_level)) +   # specify how to group data\n  geom_bar(stat = \"identity\",                        # length of bar indicates number of observations\n           width = .75,                              # space between groups\n           position = position_dodge(.8, \n                                     preserve = \"single\"), # space between bars in group\n           color = \"black\") +                        # line color of bar\n  scale_fill_manual(values = c(\"#4E5283\", \n                               \"#7871AA\", \n                               \"#D9BBF9\",\n                               \"#ECE0F8\",\n                               \"#AA9FB1\")) +      # modify for custom colors\n  labs(x = \"deicer type\",                    # x-axis title\n       y = \"% of seeds that did not germinate\",  # y-axis title\n       title = \"Data set section A\") +     \n  theme_classic() +                                  # specify theme\n  theme(legend.position = \"bottom\")                  # legend position \n```\n\n::: {.cell-output-display}\n![](C04_analyze_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# create table with % germinated\nsummary <- germination_B |>\n  group_by(deicer, treatment_level) |> # group data by treatment\n  count(germination) |>                # count number seeds germinated\n  mutate(percent = n/sum(n)*100)       # calculate proportion\n\n# subset data to show % not germinated ----\nno_germination <- summary |>\n  filter(germination == \"germinated\")\n\n# create bar plot with frequency\nggplot(no_germination, aes(x = deicer,                  # specify categories on x axis\n                        y = percent,\n                        fill = treatment_level)) +   # specify how to group data\n  geom_bar(stat = \"identity\",                        # length of bar indicates number of observations\n           width = .75,                              # space between groups\n           position = position_dodge(.8, \n                                     preserve = \"single\"), # space between bars in group\n           color = \"black\") +                        # line color of bar\n  scale_fill_manual(values = c(\"#4E5283\", \n                               \"#7871AA\", \n                               \"#D9BBF9\",\n                               \"#ECE0F8\",\n                               \"#AA9FB1\")) +      # modify for custom colors\n  labs(x = \"deicer type\",                    # x-axis title\n       y = \"% of seeds that did not germinate\",  # y-axis title\n       title = \"Data set section B\") +     \n  theme_classic() +                                  # specify theme\n  theme(legend.position = \"bottom\")                  # legend position \n```\n\n::: {.cell-output-display}\n![](C04_analyze_files/figure-html/unnamed-chunk-11-2.png){width=672}\n:::\n:::\n\n:::\n\nA lot of times it can be helpful to generate several exploratory plots that allow us to think through the data set. So let's create a similar visualization that shows the proportion for each treatment that *did not germinate* as this might let us see certain patterns more clearly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create table with % germinated\nsummary <- germination_ex |>\n  group_by(deicer, treatment_level) |> # group data by treatment\n  count(germination) |>                # count number seeds germinated\n  mutate(percent = n/sum(n)*100)       # calculate proportion\n\n# subset data to show % not germinated ----\nno_germination <- summary |>\n  filter(germination == \"no_germination\")\n\n# create bar plot with frequency\nggplot(no_germination, aes(x = deicer,                  # specify categories on x axis\n                        y = percent,\n                        fill = treatment_level)) +   # specify how to group data\n  geom_bar(stat = \"identity\",                        # length of bar indicates number of observations\n           width = .75,                              # space between groups\n           position = position_dodge(.8, \n                                     preserve = \"single\"), # space between bars in group\n           color = \"black\") +                        # line color of bar\n  scale_fill_manual(values = c(\"#4E5283\", \n                               \"#7871AA\", \n                               \"#D9BBF9\",\n                               \"#ECE0F8\",\n                               \"#AA9FB1\")) +      # modify for custom colors\n  labs(x = \"deicer type\",                    # x-axis title\n       y = \"% of seeds that did not germinate\") +                  # y-axis title\n  theme_classic() +                                  # specify theme\n  theme(legend.position = \"bottom\")                  # legend position \n```\n\n::: {.cell-output-display}\n![Comparison of germination inhibition of mung beans for different deicers and concentration levels (high = 10mg/L, medium = 1 mg/L, low = 0.1 mgl/L).](C04_analyze_files/figure-html/fig-germination-inhibition-1.png){#fig-germination-inhibition width=672}\n:::\n:::\n\n\n::: {.callout-tip title=\"Give it a try\"}\nModify the code to create a similar visualization for your data sets.\n:::\n\n::: {.callout-note title=\"Answer\" collapse=\"true\"}\n\n::: {.cell}\n\n```{.r .cell-code}\n# create table with % germinated\nsummary <- germination_A |>\n  group_by(deicer, treatment_level) |> # group data by treatment\n  count(germination) |>                # count number seeds germinated\n  mutate(percent = n/sum(n)*100)       # calculate proportion\n\n# subset data to show % not germinated ----\nno_germination <- summary |>\n  filter(germination == \"no_germination\")\n\n# create bar plot with frequency\nggplot(no_germination, aes(x = deicer,                  # specify categories on x axis\n                        y = percent,\n                        fill = treatment_level)) +   # specify how to group data\n  geom_bar(stat = \"identity\",                        # length of bar indicates number of observations\n           width = .75,                              # space between groups\n           position = position_dodge(.8, \n                                     preserve = \"single\"), # space between bars in group\n           color = \"black\") +                        # line color of bar\n  scale_fill_manual(values = c(\"#4E5283\", \n                               \"#7871AA\", \n                               \"#D9BBF9\",\n                               \"#ECE0F8\",\n                               \"#AA9FB1\")) +      # modify for custom colors\n  labs(x = \"deicer type\",                    # x-axis title\n       y = \"% of seeds that did not germinate\",  # y-axis title\n       title = \"Data set section A\") +     \n  theme_classic() +                                  # specify theme\n  theme(legend.position = \"bottom\")                  # legend position \n```\n\n::: {.cell-output-display}\n![](C04_analyze_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# create table with % germinated\nsummary <- germination_B |>\n  group_by(deicer, treatment_level) |> # group data by treatment\n  count(germination) |>                # count number seeds germinated\n  mutate(percent = n/sum(n)*100)       # calculate proportion\n\n# subset data to show % not germinated ----\nno_germination <- summary |>\n  filter(germination == \"no_germination\")\n\n# create bar plot with frequency\nggplot(no_germination, aes(x = deicer,                  # specify categories on x axis\n                        y = percent,\n                        fill = treatment_level)) +   # specify how to group data\n  geom_bar(stat = \"identity\",                        # length of bar indicates number of observations\n           width = .75,                              # space between groups\n           position = position_dodge(.8, \n                                     preserve = \"single\"), # space between bars in group\n           color = \"black\") +                        # line color of bar\n scale_fill_manual(values = c(\"#4E5283\", \n                               \"#7871AA\", \n                               \"#D9BBF9\",\n                               \"#ECE0F8\",\n                               \"#AA9FB1\")) +      # modify for custom colors\n  labs(x = \"deicer type\",                    # x-axis title\n       y = \"% of seeds that did not germinate\",  # y-axis title\n       title = \"Data set section B\") +     \n  theme_classic() +                                  # specify theme\n  theme(legend.position = \"bottom\")                  # legend position \n```\n\n::: {.cell-output-display}\n![](C04_analyze_files/figure-html/unnamed-chunk-13-2.png){width=672}\n:::\n:::\n\n:::\n\n::: {.callout-tip title=\"Give it a try\"}\nUsually for your report you would chose to either include a table or a visualization that summarizes your data. Here you would also need to decide whether the germination or inhibition version of your figure is more informative.\n\nIn either case you would include a descriptive figure or table title/caption that describes how to interpret the figure. As a rule of thumb, you should have enough information in the caption that the reader can understand the figure even without reading the methods/results.\n\nThen you should describe your results referencing your figure/table, however, your reader should be able to have the full picture of your results even without seeing the actual figure/table. A good template to use is to start with the broad pattern and then highlight important details. A good description of results contextualizes them for the reader. For example, instead of just listing out values provide context and help your reader see the patterns by using terms like \"higher\" \"lower\", \"similar\" or highlighting certain results as \"notably, ...\", \"except for...\". You have already done all the thinking, guide your reader through what you've found.\n\nDescribe your results. Remember, at this point you should not be interpreting them. Consider this thinking out loud in a way where you have a set of notes that you can then edit for your report.\n:::\n\n::: {.callout-note title=\"Answer\" collapse=\"true\"}\nYour description could look something like this:\n\nBroad pattern:\n\n> Mung beans exposed to rock salt had over 70% lower germination success compared to the control.\n\nor\n\n> Both rock salt and the commercial blend show a similar pattern of a dose-dependent relationship where germination success decreases with increasing concentrations.\n\nDetails\n\n> Overall, 93% germinated in the control, while only 20% germinated for the highest rock salt concentration (Figure xx).\n\nor\n\n> However, this effect was strong for rock salt (18 - 55% germination success) compared to the commercial blend (40 - 83% germination success).\n\nIt's important that we add this context of actual numbers because it is quite different if 100% germinated in the control and 78% in the experimental treatment or something more similar to what we observe here.\n\nHere are some additional examples of what a description could look like:\n\n**Emphasize on \"Broad Pattern First, Then Details\" formula:**\n\nOverall, germination rates varied among deicer treatments, with rock salt having the strongest negative impact, the cheese brine having the least impact, and the commercial blend showing an intermediate effect. The control group had the highest germination rate (91.67%), indicating baseline germination without deicer exposure.\n\nAmong the treatments, rock salt at high concentration had the lowest germination (18.33%), with a dose-dependent increase at medium (46.67%) and low (55.00%) concentrations. The commercial blend also showed a negative effect, but not as severe as rock salt, with germination increasing from 40.00% at high concentration to 60.00% at medium and 83.33% at low.\n\nIn contrast, the cheese brine had relatively little impact on germination. Even at the highest concentration, 65.00% of seeds germinated, and the rates at medium (88.33%) and low (86.67%) were similar to the control.\n\n**Emphasis on Highlighting Notable Findings**\n\nNotably, the rock salt treatment had the lowest germination rates, with only 18.33% of seeds germinating at the highest concentration. This is a stark contrast to the control (91.67%) and even the lowest rock salt concentration (55.00%). The commercial blend also reduced germination, but the effect was not as strong, with 40.00% germination at the highest concentration and an increase to 83.33% at the lowest concentration.\n\nInterestingly, the cheese brine had the least effect, with germination at its highest concentration (65.00%) still higher than the rock salt and commercial blend at the same level. Medium and low cheese brine concentrations (88.33% and 86.67%) were nearly identical to the control, suggesting minimal impact.\n\n**Emphasis on Highlighting Patterns with Comparative Terms**\n\nGermination rates were lowest for rock salt, with a strong dose-dependent effect: only 18.33% of seeds germinated at high concentration, but rates increased at medium (46.67%) and low (55.00%) levels. The commercial blend also reduced germination, but its effects were less severe than rock salt, with the highest concentration resulting in 40.00% germination and the lowest concentration nearly matching the control (83.33% vs. 91.67%).\n\nIn contrast, the cheese brine had the least impact on germination. Even at the highest concentration (65.00%), germination remained substantially higher than rock salt or the commercial blend at equivalent concentrations. Medium and low concentrations of cheese brine (88.33% and 86.67%) were very similar to the control, indicating a minimal negative effect.\n:::\n\nDescriptive or summary statistics are the important first step to summarizing our findings. However, at this point we don't know if our observed differences in germination success are just due to sampling error or if they actually represent reality. For example let's say that 42 seeds germinate in one treatment and 43 in another - are those numbers actually different from each other or does it fall within the natural variability of germination?\n\n### Test for statistical significance\n\nTo test whether differences in the summary statistics are actually different from each other we need to first determine what the distribution of observed germination rates when there is no difference among treatments. We would expect that distribution to look like a normal distribution where the most commonly observed germination rate is closest to the \"real value\" and the less likely/more extreme values to be less frequently observed. Then we can compare that to our actual observations and determine if our observation falls into that distribution or not. Essentially we want to quantify how likely it is that we would observe our germination rates if there is no effect.\n\nAnother way of stating this is to say that we want to make sure that our results are not due to sampling error, i.e. that our sample represents the true popoulation (i.e. all radish seeds) as a whole.\n\n::: {.callout-tip title=\"Consider this\"}\nDiscuss what common factors we need consider to avoid bias in your sample due to **sampling error**.\n:::\n\n::: {.callout-note title=\"Answer\" collapse=\"true\"}\nThe main causes are:\n\n-   **small sample size**: You would want to make sure that you are snagging enough individuals from each species to ensure that you are capturing the full range of body sizes for each species. The larger you sample size, the more likely you not only have individuals representing that full range, you should also end up with proportionally the same number of individuals in each weight category in your sample as there are in the entire population.\n-   **non-random sampling**: You need to make sure that you are sampling in a non-random manner. If you think the tiny ones are cuter and start picking up those more frequently then you would end up with a biased sample. If you are lazy, and just check the areas near your station, you might end up biasing towards larger ones e.g. because that is a spot where more food is available. If you are trying to spot them from far off and then driving towards them instead of having e.g. a random sampling grid you might only be spotting the larger ones etc.\n-   **outliers** can cause sampling error especially if the sample size is small. This is generally not something you can avoid by your sampling strategy, generally you want to have a sample size that is large enough that you can identify outliers.\n:::\n\nWhen we are making inferences based on our data set either by generalizing from the sample to the population as a whole or when testing a specific hypothesis based on the data we've collected, we need to make sure that our conclusion are erroneous due to sampling error. Therefore, once we've calculated our descriptive statistics we will generally ask the question \"**What is the probability that our results are the results of sampling error and do not reflect reality?**\" and then use statistical tests to quantify that probability. The probability of results being due to sampling error increase the smaller our sample size is, the more variability that is observed, and the smaller the difference between metrics\\[\\^a05_inferent-stats-3\\] being compared.\n\nHypothesis testing is a formal process to make inferences about a population based on sample data. It involves evaluating two competing hypotheses to determine if the results are due to sampling error alone or are representative of the population. The key steps are the same, regardless of the the specific test being applied.\n\n1.  Define your research question or goal.\n2.  Specify what measurements you plan to compare and collect the data.\n3.  State your your null and alternate hypothesis and predict the outcome assuming the null hypothesis is true.\n4.  Specify a significance threshold.\n5.  Generate sampling distributions and calculate your test statistic.\n6.  Get the p-value.\n7.  Interpret the results and draw conclusions.\n\nWe have already gone through step 1 and 2 when we designed our experiment.\n\n#### Step 3: State your your null and alternate hypothesis and predict the outcome assuming the null hypothesis is true.\n\nIf you go back to the hypothesis you formulated, you would have created an \"if-then-because\" statement. We've said that the \"because\" component is your research hypothesis. This is your reasoning of why you expect to see a certain outcome.\n\nThe \"if-then\" component specifies what you would expect to observe in your data set. Now we need to restate this as a statistical hypothesis in the form of a null ($H_{O}$) and alternate ($H_{a}$ or $H_{1}$) hypothesis so we can mathematically test it by quantifying the probability that our results are due to chance alone.\n\nThe **null hypothesis** $H_{O}$ states what our measurements will look like when there is no change or no effect in the population, or no relationship or no difference among groups being compared.\n\nAt first, stating our hypothesis as \"there is no difference\" seems a bit odd because that's not normally what we are interested in. However, it is actually quite difficult to prove an idea but much easier to **disprove** and idea. Therefore, we want to formulate a hypothesis that we can falsify. If the sample provides enough evidence against the null hypothesis then we can **reject** the hypothesis, otherwise we **fail to reject** the null hypothesis[^c04_analyze-1].\n\n[^c04_analyze-1]: Be careful not to use phrases like \"we proved\" or we \"accept\" the null hypothesis.\n\nThe **alternate hypothesis** $H_{a}$ is the complement to the null hypothesis; they should be mutually exclusive in that only one can be true at a time. The alternative hypothesis is a claim that there is an effect in the population. When you formulate your alternative hypothesis you are usually going to use phrases like \"there is an effect\", \"there is a difference\", \"there is a relationship\".\n\n::: {.callout-tip title=\"Give it a try\"}\nYou can use a standard way of formulating your null hypothesis by identifying your **dependent** and **independent variable** of your experiment.\n\nFor the null hypothesis you will always state that the **Independent variable** does not affect your **dependent variable**.\n\nSimilarly, you can use a standard way of formulating your alternate hypothesis by identifying your **dependent** and **independent variable** of your experiment. In this case, you will always state that the **Independent variable** does affect your **dependent variable**.\n\nState your null and alternative hypothesis and predict the outcome if the claim is true.\n:::\n\n::: {.callout-note title=\"Answer\" collapse=\"true\"}\nYour null hypothesis is a claim that there is no effect:\n\n-   $H_{0}$: Deicers do not have an effect on the germination rate of radish seeds.\n-   Prediction: The number of seeds that germinate are not different between the experimental treatments.\n\nThe alternative hypothesis is a claim that there is an observed effect.\n\n-   $H_{a}$: Deicers have a negative effect on the germination rate of radish seeds.\n-   Prediction: We will observe differences in germination rates among the treatments.\n:::\n\n#### Step 4: Specify a significance threshold.\n\nNow that we have stated our null hypothesis we can assess the probability of obtaining our observed results if our null hypothesis is true. However, before we do that we need to decide how far off from the null hypothesis we will let our observations be before we reject the null hypothesis.\n\nWe do this by specifying the significance level $\\alpha$. This is our predetermined threshold for statistical significance.\n\n-   if our p-value is higher than $\\alpha$ we fail to reject the null hypothesis and our results are not statistically significant.\n-   if our p-value is smaller than $\\alpha$ we reject the null hypothesis and report our results as statistically significant.\n\nTypically, $\\alpha$ is set to 0.05 (5%) but for a more conservative test it can be set to a lower value such as 0.01 (1%).\n\n::: {.callout-tip title=\"Consider this\"}\nWe will specify our significance threshold $\\alpha$ as 0.05.\n\nExplain what this means and why it is important for us to specify this.\n:::\n\n::: {.callout-note title=\"Answer\" collapse=\"true\"}\nThis means that if our observed results have a less than 5% probability occurring according to our null distribution we will reject our null hypothesis.\n:::\n\n#### Step 5: Calculate your test statistic and generate sampling distribution and Step 6: Get your p-value.\n\nNow we are ready to calculate our test statistic - we will combine this with getting our p-value.\n\nA test statistic measures how far the empirical observations are from the expectations based on the null hypothesis. Even though the exact test statistic you apply will depend on the data and type of variable you are assessing, they are all based on comparing spread of the data within a category (within-group variance) to how different categories are from each other (between-group variance). For large between-group variance (little/no overlap between groups) the more unlikely it is that the differences between these groups is due to chance alone (small p-value). By contrast, for a high within-group and low between-group variance the more likely the differences you are observing are due to chance alone (high p-value).\n\nFor any statistical test we calculating a test-statistic that is specific to the type of metric we are comparing (here that is a frequency). Then we create a null distribution that assumes that there actually is no difference between the categories we are comparing. Essentially, we are shuffling the labels across the data points and re-calculating the test- statistic over and over again to create a distribution. Finally, we will need to see if our and where our observed test statistic falls relative to that distribution.\n\nTypically, a $𝛘^2$ test is used to evaluate the difference between frequencies/categorical variables. The $\\chi^{2}$ test statistic will account for sample size and the size of difference in sample frequencies. The smaller the sample size and the difference in frequencies, the more likely our sample frequencies are different due to sampling error and not because the true population frequencies are different.\n\nFor a comparison of two categorical variables, you would create a 2x2 table[^c04_analyze-2].\n\n[^c04_analyze-2]: You might remember doing this by hand in Gen Bio one to teste whether your observed phenotypes matches those predicted by a Punnet Square. This is also how you would formally test if a population is in HWE instead of just squinting at it and declaring them different.\n\n|       | Column 1 | Column 2 | Total |\n|-------|----------|----------|-------|\n| Row 1 | f11      | f12      | R1    |\n| Row 2 | f21      | f22      | R2    |\n| Total | C1       | C2       | n     |\n\nfor $f_{ij}$ being the observation in the $i$th row and the $j$th column, $C_{1}$, $C_{2}$, $R_{1}$, and $R_{2}$ are the column and row totals and $n$ is the total number of observations.\n\nThen we can calculate $\\chi^{2}$ as\n\n$$\n\\chi^{2} = \\frac{n(f_{11}f_{22}-f_{12}f_{21})^{2}}{C_{1}C_{2}R_{1}R_{2}}\n$$\n\nInstead of doing this by hand we can reformat our data set into a contingency table and use a function that performs those calculations for us.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert germination to binary outcome\ndata <- germination_ex %>%\n  mutate(germination_binary = ifelse(germination == \"germinated\", 1, 0))\n\n# Create contingency table\ngermination_table <- table(data$treatment, data$germination)\n\n# take a look at contingency table\ngermination_table\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                     \n                      germinated no_germination\n  cheese_brine_high           39             21\n  cheese_brine_low            52              8\n  cheese_brine_medium         53              7\n  comm_blend_high             24             36\n  comm_blend_low              50             10\n  comm_blend_medium           36             24\n  control_high                55              5\n  rock_salt_high              11             49\n  rock_salt_low               33             27\n  rock_salt_medium            28             32\n```\n:::\n\n```{.r .cell-code}\n# Perform Chi-Square test\nchi_test <- chisq.test(germination_table)\n\n# Print results\nprint(chi_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's Chi-squared test\n\ndata:  germination_table\nX-squared = 137.27, df = 9, p-value < 2.2e-16\n```\n:::\n:::\n\n\n::: {.callout-tip title=\"Give it a try\"}\nModify the code to perform a $𝛘^2$ test using your data set.\n\nCompare your p-value to the threshold of significance we defined above to determine how to interpret the results of your $𝛘^2$ -test.\n:::\n\n.\n\n::: {.callout-note title=\"Answer\" collapse=\"true\"}\n\n::: {.cell}\n\n```{.r .cell-code}\n# section A ----\n\n# Convert germination to binary outcome\ndata <- germination_A %>%\n  mutate(germination_binary = ifelse(germination == \"germinated\", 1, 0))\n\n# Create contingency table\ngermination_table <- table(data$treatment, data$germination)\n\n# take a look at contingency table\ngermination_table\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                   \n                    germinated no_germination\n  control_NA                59              1\n  Fusion2330_high           59              1\n  Fusion2330_low            20              0\n  Fusion2330_medium         57              3\n  Fusion2330_trace          53              7\n  NaCl_high                 39             21\n  NaCl_low                  60              0\n  NaCl_medium               58              2\n  NaCl_trace                59              1\n```\n:::\n\n```{.r .cell-code}\n# Perform Chi-Square test\nchi_test <- chisq.test(germination_table)\n\n# Print results\nprint(chi_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's Chi-squared test\n\ndata:  germination_table\nX-squared = 87.424, df = 8, p-value = 1.548e-15\n```\n:::\n\n```{.r .cell-code}\n# Section B ----\n\n# Convert germination to binary outcome\ndata <- germination_B %>%\n  mutate(germination_binary = ifelse(germination == \"germinated\", 1, 0))\n\n# Create contingency table\ngermination_table <- table(data$treatment, data$germination)\n\n# take a look at contingency table\ngermination_table\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n              \n               germinated no_germination\n  beet_high            60              0\n  beet_low             60              0\n  CaCl_high            32              7\n  CaCl_low             44             16\n  DI-water_NA          60              0\n  MgCl_high            40              2\n  MgCl_low             58              1\n  NaCl_high            39             21\n  tap-water_NA         59              1\n  urea_high            60              0\n  urea_low             60              0\n```\n:::\n\n```{.r .cell-code}\n# Perform Chi-Square test\nchi_test <- chisq.test(germination_table)\n\n# Print results\nprint(chi_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's Chi-squared test\n\ndata:  germination_table\nX-squared = 130.01, df = 10, p-value < 2.2e-16\n```\n:::\n:::\n\n:::\n\nTo give you visualization of what we just did we can use a set of functions that will generate the null distribution and calculate the test statistic and then determine the p-value based on how probable it is that we will observe that test statistic give then null distribution[^c04_analyze-3].\n\n[^c04_analyze-3]: Note: for your report, you do not need to visualize your null distribution we are doing this to help us get a better feel for how statistical tests work. In general you just report whether your results are significant or not, you do not go through the process of defining null and alternative process etc - we go through that in detail so you know what is happening under the hood.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert germination to binary outcome\ndata <- germination_ex %>%\n  mutate(germination_binary = ifelse(germination == \"germinated\", 1, 0))\n\n# Summarize germination rates per treatment\ngermination_summary <- data %>%\n  group_by(deicer, treatment_level) %>%\n  summarise(germination_rate = mean(germination_binary) * 100)\n\n# calculate observed statistic\nobserved_indep_statistic <- data %>%\n  specify(germination ~ treatment) %>%\n  calculate(stat = \"Chisq\")\n\n# generate the null distribution using randomization\nnull_distribution_simulated <- data %>%\n  specify(germination ~ treatment) %>%\n  hypothesize(null = \"independence\") %>%\n  generate(reps = 5000, type = \"permute\") %>%\n  calculate(stat = \"Chisq\")\n\n# visualize both null distributions and the test statistic!\nnull_distribution_simulated %>%\n  visualize(method = \"both\") + \n  shade_p_value(observed_indep_statistic,\n                direction = \"greater\")\n\n# calculate the p value from the observed statistic and null distribution\nnull_distribution_simulated %>%\n  get_p_value(obs_stat = observed_indep_statistic,\n              direction = \"greater\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 1\n  p_value\n    <dbl>\n1       0\n```\n:::\n\n::: {.cell-output-display}\n![Null distribution of chi-square test statistic assuming presence of plant material has no effect on radish seed growth. Bars indicates permuted null distribution, black line indicates theoretical chi-square distribution. The calculated chi-square test statistic is indicated by the red line. Values observed in the null distribution that are more extreme that the t-statistic calculated for the empirical data set are shaded in red.](C04_analyze_files/figure-html/fig-null-dist-chi-test-1.png){#fig-null-dist-chi-test width=672}\n:::\n:::\n\n\nOur last step is to compare our p-value to our $\\alpha$ value. However, we are comparing a bunch of different treatments, all we really know at this point is that there are significant differences among ***all*** the different treatments.\n\nIn order to make statements whether there are significant differences among specific treatments we need to make pairwise comparisons. We could either do this by comparing each experimental treatment to the control or since we do want to know how the different deicers compare to each other, we can run pairwise comparisons among all treatments.\n\nBefore you worry about the amount of comparisons you need to run, here is the power of coding, we can create a `data.frame` that holds all of our possible combinations and then run a loop that takes each pair, runs a $𝛘^2$ test and then extracts the p-value and puts it into a new `data.frame` for us.\n\nTo make it easier to compare, we'll print a table that just shows the significant pairwise comparisons. We will use two methods to adjust for multiple comparisons. We need to do this because if you make a whole bunch of comparisons by chance alone some of them are going to be significant.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert germination to binary outcome\ndata <- germination_ex %>%\n  mutate(germination_binary = ifelse(germination == \"germinated\", 1, 0))\n\n# Get unique treatment groups\ntreatments <- unique(data$treatment)\n\n# Get all possible pairwise comparisons\npairwise_comparisons <- combn(treatments, 2, simplify = FALSE)\n\n# Initialize a list to store test results\nchi_square_results <- list()\n\n# Loop through each pairwise combination and perform Chi-Square test\nfor (pair in pairwise_comparisons) {\n  # Subset data for the two treatments\n  subset_data <- data %>% filter(treatment %in% pair)\n  \n  # Create contingency table\n  germination_table <- table(subset_data$treatment, subset_data$germination)\n  \n  # Perform Chi-Square test\n  chi_test <- chisq.test(germination_table)\n  \n  # Store results\n  chi_square_results[[paste(pair, collapse = \" vs. \")]] <- chi_test$p.value\n}\n\n# Convert results to a data frame\nresults_df <- data.frame(\n  comparison = names(chi_square_results),\n  p_value = unlist(chi_square_results)    # Extract raw p-values\n)\n\n# Adjust for multiple comparisons\nresults_df$bonferroni = p.adjust(results_df$p_value, method = \"bonferroni\")\nresults_df$fdr = p.adjust(results_df$p_value, method = \"fdr\")\n\n# Print the results table with significant differences\nresults_df %>%\n  arrange(p_value) %>%\n  filter(p_value <= 0.05) %>% \n  kable(row.names = FALSE)\n```\n\n::: {.cell-output-display}\n|comparison                                |   p_value| bonferroni|       fdr|\n|:-----------------------------------------|---------:|----------:|---------:|\n|rock_salt_high vs. control_high           | 0.0000000|  0.0000000| 0.0000000|\n|rock_salt_high vs. cheese_brine_medium    | 0.0000000|  0.0000000| 0.0000000|\n|rock_salt_high vs. cheese_brine_low       | 0.0000000|  0.0000000| 0.0000000|\n|rock_salt_high vs. comm_blend_low         | 0.0000000|  0.0000000| 0.0000000|\n|comm_blend_high vs. control_high          | 0.0000000|  0.0000003| 0.0000001|\n|cheese_brine_medium vs. comm_blend_high   | 0.0000001|  0.0000044| 0.0000007|\n|rock_salt_medium vs. control_high         | 0.0000003|  0.0000124| 0.0000018|\n|cheese_brine_low vs. comm_blend_high      | 0.0000003|  0.0000141| 0.0000018|\n|rock_salt_high vs. cheese_brine_high      | 0.0000006|  0.0000259| 0.0000029|\n|comm_blend_high vs. comm_blend_low        | 0.0000027|  0.0001206| 0.0000119|\n|rock_salt_medium vs. cheese_brine_medium  | 0.0000029|  0.0001306| 0.0000119|\n|rock_salt_high vs. comm_blend_medium      | 0.0000072|  0.0003229| 0.0000269|\n|rock_salt_medium vs. cheese_brine_low     | 0.0000084|  0.0003794| 0.0000292|\n|rock_salt_low vs. control_high            | 0.0000146|  0.0006558| 0.0000468|\n|rock_salt_medium vs. comm_blend_low       | 0.0000584|  0.0026280| 0.0001752|\n|rock_salt_high vs. rock_salt_low          | 0.0000695|  0.0031259| 0.0001954|\n|rock_salt_low vs. cheese_brine_medium     | 0.0001186|  0.0053356| 0.0003097|\n|comm_blend_medium vs. control_high        | 0.0001239|  0.0055741| 0.0003097|\n|rock_salt_low vs. cheese_brine_low        | 0.0003002|  0.0135107| 0.0007111|\n|cheese_brine_medium vs. comm_blend_medium | 0.0008474|  0.0381322| 0.0019030|\n|cheese_brine_high vs. control_high        | 0.0008881|  0.0399639| 0.0019030|\n|rock_salt_low vs. comm_blend_low          | 0.0015626|  0.0703187| 0.0031963|\n|rock_salt_high vs. rock_salt_medium       | 0.0018182|  0.0818182| 0.0035573|\n|cheese_brine_low vs. comm_blend_medium    | 0.0019585|  0.0881307| 0.0036721|\n|cheese_brine_high vs. cheese_brine_medium | 0.0050187|  0.2258436| 0.0090337|\n|comm_blend_medium vs. comm_blend_low      | 0.0084492|  0.3802130| 0.0146236|\n|cheese_brine_high vs. comm_blend_high     | 0.0104901|  0.4720563| 0.0168760|\n|cheese_brine_high vs. cheese_brine_low    | 0.0105006|  0.4725269| 0.0168760|\n|rock_salt_high vs. comm_blend_high        | 0.0159498|  0.7177396| 0.0247496|\n|cheese_brine_high vs. comm_blend_low      | 0.0370219|  1.0000000| 0.0555329|\n|comm_blend_high vs. comm_blend_medium     | 0.0446097|  1.0000000| 0.0647560|\n:::\n:::\n\n\n::: {.callout-tip title=\"Give it a try\"}\nModify the code above to run the pairwise comparisons on your data set.\n:::\n\n::: {.callout-note title=\"Answer\" collapse=\"true\"}\n\n::: {.cell}\n\n```{.r .cell-code}\n## Section A ----\n\n# Convert germination to binary outcome\ndata <- germination_A %>%\n  mutate(germination_binary = ifelse(germination == \"germinated\", 1, 0))\n\n# Get unique treatment groups\ntreatments <- unique(data$treatment)\n\n# Get all possible pairwise comparisons\npairwise_comparisons <- combn(treatments, 2, simplify = FALSE)\n\n# Initialize a list to store test results\nchi_square_results <- list()\n\n# Loop through each pairwise combination and perform Chi-Square test\nfor (pair in pairwise_comparisons) {\n  # Subset data for the two treatments\n  subset_data <- data %>% filter(treatment %in% pair)\n  \n  # Create contingency table\n  germination_table <- table(subset_data$treatment, subset_data$germination)\n  \n  # Perform Chi-Square test\n  chi_test <- chisq.test(germination_table)\n  \n  # Store results\n  chi_square_results[[paste(pair, collapse = \" vs. \")]] <- chi_test$p.value\n}\n\n# Convert results to a data frame\nresults_df <- data.frame(\n  comparison = names(chi_square_results),\n  p_value = unlist(chi_square_results)    # Extract raw p-values\n)\n\n# Adjust for multiple comparisons\nresults_df$bonferroni = p.adjust(results_df$p_value, method = \"bonferroni\")\nresults_df$fdr = p.adjust(results_df$p_value, method = \"fdr\")\n\n# Print the results table with significant differences\nresults_df %>%\n  arrange(p_value) %>%\n  filter(p_value <= 0.05) %>% \n  kable(row.names = FALSE)\n```\n\n::: {.cell-output-display}\n|comparison                      |   p_value| bonferroni|       fdr|\n|:-------------------------------|---------:|----------:|---------:|\n|NaCl_high vs. NaCl_low          | 0.0000015|  0.0000557| 0.0000557|\n|control_NA vs. NaCl_high        | 0.0000074|  0.0002656| 0.0000558|\n|Fusion2330_high vs. NaCl_high   | 0.0000074|  0.0002656| 0.0000558|\n|NaCl_high vs. NaCl_trace        | 0.0000074|  0.0002656| 0.0000558|\n|Fusion2330_low vs. NaCl_low     | 0.0000077|  0.0002788| 0.0000558|\n|NaCl_high vs. NaCl_medium       | 0.0000299|  0.0010747| 0.0001791|\n|Fusion2330_medium vs. NaCl_high | 0.0001046|  0.0037651| 0.0005379|\n|Fusion2330_trace vs. NaCl_high  | 0.0050187|  0.1806749| 0.0212519|\n|Fusion2330_low vs. NaCl_high    | 0.0053130|  0.1912668| 0.0212519|\n|Fusion2330_trace vs. NaCl_low   | 0.0194406|  0.6998618| 0.0699862|\n:::\n\n```{.r .cell-code}\n## Section B ----\n\n# Convert germination to binary outcome\ndata <- germination_ex %>%\n  mutate(germination_binary = ifelse(germination == \"germinated\", 1, 0))\n\n# Get unique treatment groups\ntreatments <- unique(data$treatment)\n\n# Get all possible pairwise comparisons\npairwise_comparisons <- combn(treatments, 2, simplify = FALSE)\n\n# Initialize a list to store test results\nchi_square_results <- list()\n\n# Loop through each pairwise combination and perform Chi-Square test\nfor (pair in pairwise_comparisons) {\n  # Subset data for the two treatments\n  subset_data <- data %>% filter(treatment %in% pair)\n  \n  # Create contingency table\n  germination_table <- table(subset_data$treatment, subset_data$germination)\n  \n  # Perform Chi-Square test\n  chi_test <- chisq.test(germination_table)\n  \n  # Store results\n  chi_square_results[[paste(pair, collapse = \" vs. \")]] <- chi_test$p.value\n}\n\n# Convert results to a data frame\nresults_df <- data.frame(\n  comparison = names(chi_square_results),\n  p_value = unlist(chi_square_results)    # Extract raw p-values\n)\n\n# Adjust for multiple comparisons\nresults_df$bonferroni = p.adjust(results_df$p_value, method = \"bonferroni\")\nresults_df$fdr = p.adjust(results_df$p_value, method = \"fdr\")\n\n# Print the results table with significant differences\nresults_df %>%\n  arrange(p_value) %>%\n  filter(p_value <= 0.05) %>% \n  kable(row.names = FALSE)\n```\n\n::: {.cell-output-display}\n|comparison                                |   p_value| bonferroni|       fdr|\n|:-----------------------------------------|---------:|----------:|---------:|\n|rock_salt_high vs. control_high           | 0.0000000|  0.0000000| 0.0000000|\n|rock_salt_high vs. cheese_brine_medium    | 0.0000000|  0.0000000| 0.0000000|\n|rock_salt_high vs. cheese_brine_low       | 0.0000000|  0.0000000| 0.0000000|\n|rock_salt_high vs. comm_blend_low         | 0.0000000|  0.0000000| 0.0000000|\n|comm_blend_high vs. control_high          | 0.0000000|  0.0000003| 0.0000001|\n|cheese_brine_medium vs. comm_blend_high   | 0.0000001|  0.0000044| 0.0000007|\n|rock_salt_medium vs. control_high         | 0.0000003|  0.0000124| 0.0000018|\n|cheese_brine_low vs. comm_blend_high      | 0.0000003|  0.0000141| 0.0000018|\n|rock_salt_high vs. cheese_brine_high      | 0.0000006|  0.0000259| 0.0000029|\n|comm_blend_high vs. comm_blend_low        | 0.0000027|  0.0001206| 0.0000119|\n|rock_salt_medium vs. cheese_brine_medium  | 0.0000029|  0.0001306| 0.0000119|\n|rock_salt_high vs. comm_blend_medium      | 0.0000072|  0.0003229| 0.0000269|\n|rock_salt_medium vs. cheese_brine_low     | 0.0000084|  0.0003794| 0.0000292|\n|rock_salt_low vs. control_high            | 0.0000146|  0.0006558| 0.0000468|\n|rock_salt_medium vs. comm_blend_low       | 0.0000584|  0.0026280| 0.0001752|\n|rock_salt_high vs. rock_salt_low          | 0.0000695|  0.0031259| 0.0001954|\n|rock_salt_low vs. cheese_brine_medium     | 0.0001186|  0.0053356| 0.0003097|\n|comm_blend_medium vs. control_high        | 0.0001239|  0.0055741| 0.0003097|\n|rock_salt_low vs. cheese_brine_low        | 0.0003002|  0.0135107| 0.0007111|\n|cheese_brine_medium vs. comm_blend_medium | 0.0008474|  0.0381322| 0.0019030|\n|cheese_brine_high vs. control_high        | 0.0008881|  0.0399639| 0.0019030|\n|rock_salt_low vs. comm_blend_low          | 0.0015626|  0.0703187| 0.0031963|\n|rock_salt_high vs. rock_salt_medium       | 0.0018182|  0.0818182| 0.0035573|\n|cheese_brine_low vs. comm_blend_medium    | 0.0019585|  0.0881307| 0.0036721|\n|cheese_brine_high vs. cheese_brine_medium | 0.0050187|  0.2258436| 0.0090337|\n|comm_blend_medium vs. comm_blend_low      | 0.0084492|  0.3802130| 0.0146236|\n|cheese_brine_high vs. comm_blend_high     | 0.0104901|  0.4720563| 0.0168760|\n|cheese_brine_high vs. cheese_brine_low    | 0.0105006|  0.4725269| 0.0168760|\n|rock_salt_high vs. comm_blend_high        | 0.0159498|  0.7177396| 0.0247496|\n|cheese_brine_high vs. comm_blend_low      | 0.0370219|  1.0000000| 0.0555329|\n|comm_blend_high vs. comm_blend_medium     | 0.0446097|  1.0000000| 0.0647560|\n:::\n:::\n\n:::\n\n#### Step 7: Interpret the results and draw conclusions.\n\nOur last step is to compare our p-value to our $\\alpha$ value and draw conclusions. We have filtered our output of the pairwise comparisons to retain only values equal to or lower than our $\\alpha$ value but we will still need to interpret our results. Do they indicate that we should accept our null hypothesis or reject it and accept our alternative hypothesis?\n\n::: {.callout-tip title=\"Give it a try\"}\nCompare your p-value to the threshold of significance we defined above to determine how to interpret the results of your statistical test.\n\nThen update the results you formulated earlier to add this information into your description of the results.\n:::\n\n::: {.callout-note title=\"Answer\" collapse=\"true\"}\nTo determine whether the differences between treatments are statistically significant, follow these steps:\n\n1.  **Identify the p-value**: Each comparison in the table has an associated p-value, which quantifies the probability that the observed difference between treatments occurred by random chance.\n2.  **Compare to the Significance Threshold**: A common threshold for significance is **α = 0.05** (or 5%). If the **p-value is less than 0.05**, the difference between treatments is considered statistically significant, meaning it is unlikely to have occurred due to chance alone.\n3.  **Apply Multiple Comparison Corrections**: Since multiple comparisons were made, we use the **Bonferroni correction** and **False Discovery Rate (FDR) adjustment** to account for the increased likelihood of finding a significant result by chance.\n    -   **Bonferroni correction** is more conservative, adjusting the significance threshold by dividing **α** by the number of comparisons, reducing the chance of false positives.\n    -   **FDR adjustment** controls the proportion of false positives among significant results, balancing sensitivity and specificity.\n4.  **Interpret the Results**:\n    -   If the **raw p-value is below 0.05**, there is strong evidence that the difference between treatments is meaningful but really you should use the adjusted p-values.\n    -   If the **Bonferroni-adjusted p-value** remains below 0.05, the result is significant, even with strict multiple-testing corrections.\n    -   If the **FDR-adjusted p-value** is below 0.05 but the Bonferroni-adjusted value is not, the result is likely significant but should be interpreted with some caution.\n5.  **Update Your Description of Results**: If a treatment comparison is statistically significant, explicitly state this in your results section. If a comparison is **not significant** (p ≥ 0.05 after correction), mention that there is **no strong evidence of a difference** between those treatments.\n\nHere is what your results from above could look like once you have added the results from your statistical tests:\n\n**Emphasize on \"Broad Pattern First, Then Details\" formula:**\n\nOverall, germination rates varied among deicer treatments, with rock salt having the strongest negative impact, the cheese brine having the least impact, and the commercial blend showing an intermediate effect. The control group had the highest germination rate (92%), indicating baseline germination without deicer exposure.\n\nAmong the treatments, rock salt at high concentration had the lowest germination (18%), and statistical comparisons confirmed that this was significantly lower than the control (p \\< 0.001, Bonferroni and FDR adjusted). The medium (46%) and low (55%) concentrations of rock salt also significantly reduced germination compared to the control (p \\< 0.001 for medium; and low). Rock salt high was also significantly lower than cheese brine medium (p \\< 0.001) and low (p \\< 0.001), as well as the low commercial blend treatment (p \\< 0.001), suggesting a stronger effect on seed germination than other treatments.\n\nThe commercial blend also showed a negative effect, but not as severe as rock salt, with germination increasing from 40% at high concentration to 60% at medium and 83% at low. The highest concentration of commercial blend significantly reduced germination compared to the control (p \\< 0.001) and was also significantly lower than cheese brine at both medium (p = 0.001) and low (p \\< 0.001) concentrations.\n\nIn contrast, the cheese brine had relatively little impact on germination. Even at the highest concentration, 65% of seeds germinated, which was significantly higher than rock salt high (p \\< 0.001). The medium (88%) and low (86%) concentrations of cheese brine were not significantly different from the control.\n\n**Emphasis on Highlighting Notable Findings**\n\nNotably, the rock salt treatment had the lowest germination rates, with only 18% of seeds germinating at the highest concentration. This is a stark contrast to the control (91%) and even the lowest rock salt concentration (55%). The statistical comparisons confirmed that rock salt high significantly reduced germination compared to the control (p \\< 0.001) and to cheese brine at medium and low concentrations (p \\< 0.001 for both). Germination rates for rock salt medium and low were also significantly lower than the control (p \\< 0.001 for both).\n\nThe commercial blend also significantly reduced germination, but its effects were not as strong as rock salt. The highest concentration resulted in 40% germination, which was significantly lower than the control (p \\< 0.001) and lower than cheese brine medium (p = 0.001) and cheese brine low (p \\< 0.001). However, germination in the commercial blend low treatment (83%) was not significantly different from the control.\n\nInterestingly, the cheese brine had the least effect, with germination at its highest concentration (65%) still significantly higher than rock salt at the same level (p \\< 0.001). Medium and low concentrations of cheese brine (88% and 86%) were nearly identical to the control and not significantly different, indicating minimal impact.\n\n**Emphasis on Highlighting Patterns with Comparative Terms**\n\nGermination rates were lowest for rock salt, with a strong dose-dependent effect: only 18% of seeds germinated at high concentration, but rates increased at medium (46%) and low (55%) levels. The highest concentration of rock salt significantly reduced germination compared to the control (p \\< 0.001) and was also significantly lower than cheese brine medium and low (p \\< 0.001 for both). Even rock salt at its lowest concentration was significantly different from the control (p = 0.001).\n\nThe commercial blend also reduced germination, but its effects were less severe than rock salt, with the highest concentration (40%) showing significantly lower germination than the control (p \\< 0.0001) and also significantly lower than cheese brine medium (p = 0.001) and low (p \\< 0.001). However, germination in the low commercial blend treatment (83%) was not significantly different from the control.\n\nIn contrast, the cheese brine had the least impact on germination. Even at the highest concentration (65%), germination remained substantially higher than rock salt (p = 0.0001) and was comparable to the commercial blend medium (p = 0.001). Medium and low concentrations of cheese brine (88% and 86%) were very similar to the control, with no statistically significant difference.\n:::\n\n## Seedling length\n\n### Get your data\n\nGo to the `GoogleSheet` that contains the seedling lengths for your lab and select the tab for your group. Double check that the data has been entered correctly. Then go to `File` -\\> `Download` -\\> `Tab Separated Values (.tsv)` down load your data as a tab-delimited file. Now, use your `File Explorer` if you are on a Windows computer and `Finder` of you are on a Mac and navigate to the `Downloads` folder. You should see the file you just downloaded there. Rename it to `seedling-length_plant.tsv` depending on the plant you are testing and place it in the `data` folder of your `02_Allelopathy` project folder.\n\nOnce you go back to your `Rstudio` window with your `Rproj` loaded you should see the file in your `data` folder in the `Files` pane. Double check that it is there, if not, as you instructor to help you get set up.\n\nNow we are ready to read in our seedling length data as a `data.frame` that we can compute on in `R`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# read in data\nlength_ex <- read_delim(here(\"data\", \"seedling_length-1.csv\"), delim = \",\") |>\n  clean_names() |>\n  unite(treatment, deicer, treatment_level,\n        sep = \"_\", remove = FALSE) |>\n  mutate(treatment_level = factor(treatment_level, \n                                  levels = c(\"high\", \"medium\", \"low\", \"trace\")))\n\n# read in data\nlength_A <- read_delim(here(\"data\", \"seedlings_Section-A.csv\"), delim = \",\") |>\n  clean_names() |>\n  unite(treatment, deicer, treatment_level,\n        sep = \"_\", remove = FALSE) |>\n  mutate(treatment_level = factor(treatment_level, \n                                  levels = c(\"high\", \"medium\", \"low\", \"trace\")))\n\n# read in data\nlength_B <- read_delim(here(\"data\", \"seedlings_Section-B.csv\"), delim = \",\") |>\n  clean_names() |>\n  unite(treatment, deicer, treatment_level,\n        sep = \"_\", remove = FALSE) |>\n  mutate(treatment_level = factor(treatment_level, \n                                  levels = c(\"high\", \"medium\", \"low\", \"trace\")))\n\n# take a look at first few lines\nhead(length)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                      \n1 .Primitive(\"length\")\n```\n:::\n:::\n\n\nLet's take a quick look at the sample sizes and completeness of our data sets. Remember that we are only using data on the seedlings of germinated seeds so our sample sizes should be a lot more variable. This is also why we used a sample size of 60 over three replicates so that even if we had strong inhibition that would still give us a sufficient sample size.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Example data set \nlength_ex %>%\n  group_by(deicer) %>%\n  count() %>%\n  kable()\n```\n\n::: {.cell-output-display}\n|deicer       |   n|\n|:------------|---:|\n|cheese_brine | 145|\n|comm_blend   | 131|\n|control      |  60|\n|rock_salt    | 104|\n:::\n\n```{.r .cell-code}\nlength_ex %>%\n  group_by(deicer, treatment_level, replicate) %>%\n  count() %>%\n  kable()\n```\n\n::: {.cell-output-display}\n|deicer       |treatment_level | replicate|  n|\n|:------------|:---------------|---------:|--:|\n|cheese_brine |high            |         1| 10|\n|cheese_brine |high            |         2| 11|\n|cheese_brine |high            |         3|  4|\n|cheese_brine |medium          |         1| 20|\n|cheese_brine |medium          |         2| 20|\n|cheese_brine |medium          |         3| 20|\n|cheese_brine |low             |         1| 20|\n|cheese_brine |low             |         2| 20|\n|cheese_brine |low             |         3| 20|\n|comm_blend   |high            |         1| 10|\n|comm_blend   |high            |         2| 12|\n|comm_blend   |high            |         3|  8|\n|comm_blend   |medium          |         1| 12|\n|comm_blend   |medium          |         2| 16|\n|comm_blend   |medium          |         3| 13|\n|comm_blend   |low             |         1| 20|\n|comm_blend   |low             |         2| 20|\n|comm_blend   |low             |         3| 20|\n|control      |NA              |         1| 20|\n|control      |NA              |         2| 20|\n|control      |NA              |         3| 20|\n|rock_salt    |high            |         1|  5|\n|rock_salt    |high            |         2|  5|\n|rock_salt    |high            |         3|  3|\n|rock_salt    |medium          |         1| 10|\n|rock_salt    |medium          |         2| 11|\n|rock_salt    |medium          |         3| 10|\n|rock_salt    |low             |         1| 20|\n|rock_salt    |low             |         2| 20|\n|rock_salt    |low             |         3| 20|\n:::\n\n```{.r .cell-code}\nlength_ex %>%\n  group_by(deicer, treatment_level) %>%\n  count() %>%\n  kable()\n```\n\n::: {.cell-output-display}\n|deicer       |treatment_level |  n|\n|:------------|:---------------|--:|\n|cheese_brine |high            | 25|\n|cheese_brine |medium          | 60|\n|cheese_brine |low             | 60|\n|comm_blend   |high            | 30|\n|comm_blend   |medium          | 41|\n|comm_blend   |low             | 60|\n|control      |NA              | 60|\n|rock_salt    |high            | 13|\n|rock_salt    |medium          | 31|\n|rock_salt    |low             | 60|\n:::\n:::\n\n\n::: {.callout-tip title=\"Give it a try\"}\nModify the code above to produce the same summary tables for your data set.\n:::\n\n::: {.callout-note title=\"Answer\" collapse=\"true\"}\nFor section A\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Section A data set \nlength_A %>%\n  group_by(deicer) %>%\n  count() %>%\n  kable()\n```\n\n::: {.cell-output-display}\n|deicer     |   n|\n|:----------|---:|\n|Fusion2330 | 238|\n|NaCl       | 238|\n|control    |  59|\n:::\n\n```{.r .cell-code}\nlength_A %>%\n  group_by(deicer, treatment_level, replicate) %>%\n  count() %>%\n  kable()\n```\n\n::: {.cell-output-display}\n|deicer     |treatment_level | replicate|  n|\n|:----------|:---------------|---------:|--:|\n|Fusion2330 |high            |         1| 20|\n|Fusion2330 |high            |         2| 20|\n|Fusion2330 |high            |         3| 20|\n|Fusion2330 |medium          |         1| 20|\n|Fusion2330 |medium          |         2| 19|\n|Fusion2330 |medium          |         3| 19|\n|Fusion2330 |low             |         1| 20|\n|Fusion2330 |low             |         2| 20|\n|Fusion2330 |low             |         3| 20|\n|Fusion2330 |trace           |         1| 20|\n|Fusion2330 |trace           |         2| 20|\n|Fusion2330 |trace           |         3| 20|\n|NaCl       |high            |         1| 19|\n|NaCl       |high            |         2| 20|\n|NaCl       |high            |         3| 20|\n|NaCl       |medium          |         1| 20|\n|NaCl       |medium          |         2| 20|\n|NaCl       |medium          |         3| 20|\n|NaCl       |low             |         1| 19|\n|NaCl       |low             |         2| 20|\n|NaCl       |low             |         3| 20|\n|NaCl       |trace           |         1| 20|\n|NaCl       |trace           |         2| 20|\n|NaCl       |trace           |         3| 20|\n|control    |NA              |         1| 20|\n|control    |NA              |         2| 20|\n|control    |NA              |         3| 19|\n:::\n\n```{.r .cell-code}\nlength_A %>%\n  group_by(deicer, treatment_level) %>%\n  count() %>%\n  kable()\n```\n\n::: {.cell-output-display}\n|deicer     |treatment_level |  n|\n|:----------|:---------------|--:|\n|Fusion2330 |high            | 60|\n|Fusion2330 |medium          | 58|\n|Fusion2330 |low             | 60|\n|Fusion2330 |trace           | 60|\n|NaCl       |high            | 59|\n|NaCl       |medium          | 60|\n|NaCl       |low             | 59|\n|NaCl       |trace           | 60|\n|control    |NA              | 59|\n:::\n:::\n\n\nFor section B\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Section B data set \nlength_B %>%\n  group_by(deicer) %>%\n  count() %>%\n  kable()\n```\n\n::: {.cell-output-display}\n|deicer    |   n|\n|:---------|---:|\n|CaCl      | 119|\n|DI-water  |  60|\n|MgCl      | 117|\n|NaCl      |  59|\n|Tap-water |  59|\n|beet      | 119|\n|urea      | 120|\n:::\n\n```{.r .cell-code}\nlength_B %>%\n  group_by(deicer, treatment_level, replicate) %>%\n  count() %>%\n  kable()\n```\n\n::: {.cell-output-display}\n|deicer    |treatment_level | replicate|  n|\n|:---------|:---------------|---------:|--:|\n|CaCl      |high            |         1| 39|\n|CaCl      |high            |         3| 20|\n|CaCl      |low             |         1| 40|\n|CaCl      |low             |         3| 20|\n|DI-water  |NA              |         1| 20|\n|DI-water  |NA              |         2| 20|\n|DI-water  |NA              |         3| 20|\n|MgCl      |high            |         1| 20|\n|MgCl      |high            |         2| 20|\n|MgCl      |high            |         3| 18|\n|MgCl      |low             |         1| 19|\n|MgCl      |low             |         2| 20|\n|MgCl      |low             |         3| 20|\n|NaCl      |high            |         1| 19|\n|NaCl      |high            |         2| 20|\n|NaCl      |high            |         3| 20|\n|Tap-water |NA              |         1| 20|\n|Tap-water |NA              |         2| 20|\n|Tap-water |NA              |         3| 19|\n|beet      |high            |         1| 20|\n|beet      |high            |         2| 20|\n|beet      |high            |         3| 19|\n|beet      |low             |         1| 20|\n|beet      |low             |         2| 20|\n|beet      |low             |         3| 20|\n|urea      |high            |         1| 20|\n|urea      |high            |         2| 20|\n|urea      |high            |         3| 20|\n|urea      |low             |         1| 20|\n|urea      |low             |         2| 20|\n|urea      |low             |         3| 20|\n:::\n\n```{.r .cell-code}\nlength_B %>%\n  group_by(deicer, treatment_level) %>%\n  count() %>%\n  kable()\n```\n\n::: {.cell-output-display}\n|deicer    |treatment_level |  n|\n|:---------|:---------------|--:|\n|CaCl      |high            | 59|\n|CaCl      |low             | 60|\n|DI-water  |NA              | 60|\n|MgCl      |high            | 58|\n|MgCl      |low             | 59|\n|NaCl      |high            | 59|\n|Tap-water |NA              | 59|\n|beet      |high            | 59|\n|beet      |low             | 60|\n|urea      |high            | 60|\n|urea      |low             | 60|\n:::\n:::\n\n\nThere seems to be a mislabeling issue with the CaCl petri dishes but since we are going to combine replicates we can leave it for now.\n:::\n\n### Summarize your results\n\n::: {.callout-tip title=\"Consider this\"}\nTake a look at the `data.frame` object holding your data by clicking on it in the `Environment` pane (bottom left) or using `View(object)`.\n\nDescribe how your data is organized:\n\n-   what information is in each row?\n-   what information is in each column?\n\nAssess what type of data you have\n\n-   is it continuous or categorical?\n-   what groups are you comparing?\n\nThen determine which descriptive statistics are appropriate to summarize this data set and how you would visualize your data.\n:::\n\n::: {.callout-note title=\"Answer\" collapse=\"true\"}\nEach row represents one seedling. And each column contains information for one variable.\n\nYour data is continuous; you have a length measurement in millimeters. You have various treatments which you are comparing which are a combination of the deicer type and the concentration level. This is a categorical variable.\n\nYou will want to determine the mean and standard deviation of the seedling length for both treatments. It could also be helpful to generate additional summary statistics including median, minimum and maximum values to give yourself an overview of the data.\n\nWe can use various visualizations for your data set, the first is that you can visualize the distributions using a histogram or boxplot, the second is that you can visualize the mean and standard deviation using a bar chart or similar.\n:::\n\nWe will need to summarize our results to evaluate our findings.\n\n::: {.callout-tip title=\"Consider this\"}\nSuggest 3-4 metrics to summarize your data in a meaningful way that will allow you to describe your results in the context of the hypothesis you are exploring with this experiment.\n\nExplain why you think these would be appropriate data analysis methods.\n:::\n\n::: {.callout-note title=\"Answer\" collapse=\"true\"}\nAs we have continuous data, we can use the descriptive statistics that allow us to assess the distribution (histogram), central tendency (mean, median, mode) and variability (variance, standard deviation, range) of our data.\n:::\n\nLet's start by putting together a table with summary statistics.\n\n\n::: {#tbl-summary-length .cell tbl-cap='Summary statistics for seedling length. Mean, median, standard deviation (sd), minimum (min) and maximum (max) length in millimeters for seedlings exposed to deicers at various treatment levels.'}\n\n```{.r .cell-code}\n# calculate summary stats for deicer and treatment_level\nsummary <- length_ex |>                              # specify object\n  group_by(deicer, treatment_level) |>            # group by treatment\n  summarize(mean = mean(length_mm),\n            sd = sd(length_mm),\n            min = sd(length_mm),\n            max = max(length_mm),\n            median = median(length_mm))  # calculate summary stats\n\n# print table\nsummary |>\n  kable(digits = 1)\n```\n\n::: {.cell-output-display}\n|deicer       |treatment_level | mean|  sd| min|  max| median|\n|:------------|:---------------|----:|---:|---:|----:|------:|\n|cheese_brine |high            |  7.6| 3.5| 3.5| 12.5|    8.7|\n|cheese_brine |medium          | 10.4| 2.8| 2.8| 16.8|   10.8|\n|cheese_brine |low             | 10.5| 2.3| 2.3| 14.7|   10.4|\n|comm_blend   |high            |  3.7| 1.7| 1.7|  6.8|    3.5|\n|comm_blend   |medium          |  8.4| 2.6| 2.6| 16.0|    8.1|\n|comm_blend   |low             | 10.6| 2.0| 2.0| 16.0|   10.6|\n|control      |NA              | 11.2| 2.6| 2.6| 17.8|   11.5|\n|rock_salt    |high            |  4.0| 1.6| 1.6|  6.1|    3.5|\n|rock_salt    |medium          |  6.4| 1.7| 1.7| 10.7|    6.3|\n|rock_salt    |low             | 10.5| 2.4| 2.4| 16.2|   10.6|\n:::\n:::\n\n\n::: {.callout-tip title=\"Give it a try\"}\nModify the code above to calculate additional summary statistics for your data set.\n:::\n\n::: {.callout-note title=\"Answer\" collapse=\"true\"}\nSection A data set\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# calculate summary stats for deicer and treatment_level\nsummary <- length_A |>                      # specify object\n  group_by(deicer, treatment_level) |>      # group by treatment\n  summarize(mean = mean(length_mm),\n            sd = sd(length_mm),\n            min = sd(length_mm),\n            max = max(length_mm),\n            median = median(length_mm))     # calculate summary stats\n\n# print table\nsummary |>\n  kable(digits = 1)\n```\n\n::: {.cell-output-display}\n|deicer     |treatment_level | mean|   sd|  min| max| median|\n|:----------|:---------------|----:|----:|----:|---:|------:|\n|Fusion2330 |high            | 46.1| 22.1| 22.1|  85|   48.0|\n|Fusion2330 |medium          | 52.7| 17.6| 17.6|  93|   54.0|\n|Fusion2330 |low             | 59.6| 22.2| 22.2| 111|   63.0|\n|Fusion2330 |trace           | 52.9| 25.6| 25.6| 105|   48.0|\n|NaCl       |high            | 15.2|  8.2|  8.2|  43|   13.0|\n|NaCl       |medium          | 46.9| 25.0| 25.0|  89|   53.5|\n|NaCl       |low             | 49.1| 19.0| 19.0|  99|   54.0|\n|NaCl       |trace           | 66.0| 24.8| 24.8| 144|   65.0|\n|control    |NA              | 52.8| 21.5| 21.5| 105|   55.0|\n:::\n:::\n\n\nSection B data set\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# calculate summary stats for deicer and treatment_level\nsummary <- length_B |>                      # specify object\n  group_by(deicer, treatment_level) |>      # group by treatment\n  summarize(mean = mean(length_mm),\n            sd = sd(length_mm),\n            min = sd(length_mm),\n            max = max(length_mm),\n            median = median(length_mm))     # calculate summary stats\n\n# print table\nsummary |>\n  kable(digits = 1)\n```\n\n::: {.cell-output-display}\n|deicer    |treatment_level | mean|   sd|  min| max| median|\n|:---------|:---------------|----:|----:|----:|---:|------:|\n|CaCl      |high            | 13.1| 10.8| 10.8|  49|   10.0|\n|CaCl      |low             | 12.3|  6.8|  6.8|  30|   10.0|\n|DI-water  |NA              | 46.4| 15.8| 15.8|  75|   48.5|\n|MgCl      |high            | 13.7|  5.1|  5.1|  25|   13.0|\n|MgCl      |low             | 13.2|  5.6|  5.6|  35|   13.0|\n|NaCl      |high            | 15.2|  8.2|  8.2|  43|   13.0|\n|Tap-water |NA              | 43.1| 18.8| 18.8|  81|   45.0|\n|beet      |high            | 50.9| 21.3| 21.3|  86|   53.0|\n|beet      |low             | 47.3| 15.1| 15.1|  85|   46.5|\n|urea      |high            | 33.2| 15.3| 15.3|  64|   30.0|\n|urea      |low             | 40.1| 15.5| 15.5|  77|   40.5|\n:::\n:::\n\n:::\n\nAgain, data visualizations are an important tool to summarize and present your data. Let's start by visualizing our data with a box plot which emphasize the distribution of our values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# make box plots\nggplot(length_ex,                                   # specify object to plot\n       aes(x = deicer,                              # column on x-axis\n           y = length_mm,                           # column on y-axis\n           fill = treatment_level)) +              # column to group by\n  geom_boxplot(position = position_dodge2(preserve = \"single\")) + # plot type\n  scale_fill_manual(values = c(\"#4E5283\", \n                               \"#7871AA\", \n                               \"#D9BBF9\",\n                               \"#AA9FB1\")) +         # modify for custom colors\n  labs(x = \"deicer\",                                 # x-axis title\n      y = \"seedling length [mm]\") +                  # y-axis title\n  theme_classic() +                                  # specify theme\n  theme(legend.position = \"bottom\")                  # legend position \n```\n\n::: {.cell-output-display}\n![Seedling length distribution after 1 week for radish seeds explosed to various deicers for different concentrations.](C04_analyze_files/figure-html/fig-length-histogram-1.png){#fig-length-histogram width=672}\n:::\n:::\n\n\nA **boxplot** or box-and-whisker plot is a graphical summary of a dataset that helps visualize its distribution, variability, and potential outliers. Boxplots are useful for comparing distributions across different groups, making them a powerful tool for visualizing overall patterns in data. A shorter box means less variability, while a longer box indicates more spread in the middle 50% of the data. If the median is centered in the box, the data is symmetrical; if it’s closer to one side, the data is skewed. Outliers suggest unusual values that may need further investigation.\n\nHere’s how to interpret it:\n\n1.  **Box (Interquartile Range, IQR):** The box represents the middle 50% of the data (the interquartile range, or IQR), spanning from the first quartile (Q1, 25th percentile) to the third quartile (Q3, 75th percentile). The line inside the box marks the median (Q2, 50th percentile)—the middle value of the dataset.\n\n2.  **Whiskers (Data Spread):** The whiskers extend to the smallest and largest values within a reasonable range (typically 1.5 × IQR from Q1 and Q3). If whiskers are longer on one side, it suggests skewness (asymmetry in the data distribution).\n\n3.  **Outliers (Unusual Data Points):** Dots or asterisks outside the whiskers indicate potential outliers, meaning values that are unusually high or low compared to the rest of the data.\n\n::: {.callout-tip title=\"Give it a try\"}\nModify the code to produce box plots for your own data set.\n:::\n\n::: {.callout-note title=\"Answer\" collapse=\"true\"}\nSection A data set\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# make box plots\nggplot(length_A,                                   # specify object to plot\n       aes(x = deicer,                              # column on x-axis\n           y = length_mm,                           # column on y-axis\n           fill = treatment_level)) +              # column to group by\n  geom_boxplot(position = position_dodge2(preserve = \"single\")) + # plot type\n  scale_fill_manual(values = c(\"#4E5283\", \n                               \"#7871AA\", \n                               \"#D9BBF9\",\n                               \"#AA9FB1\")) +         # modify for custom colors\n  labs(x = \"deicer\",                                 # x-axis title\n      y = \"seedling length [mm]\") +                  # y-axis title\n  theme_classic() +                                  # specify theme\n  theme(legend.position = \"bottom\")                  # legend position \n```\n\n::: {.cell-output-display}\n![](C04_analyze_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\nSection B data set\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# make box plots\nggplot(length_B,                                   # specify object to plot\n       aes(x = deicer,                              # column on x-axis\n           y = length_mm,                           # column on y-axis\n           fill = treatment_level)) +              # column to group by\n  geom_boxplot(position = position_dodge2(preserve = \"single\")) + # plot type\n  scale_fill_manual(values = c(\"#4E5283\", \n                               \"#7871AA\", \n                               \"#D9BBF9\",\n                               \"#AA9FB1\")) +         # modify for custom colors\n  labs(x = \"deicer\",                                 # x-axis title\n      y = \"seedling length [mm]\") +                  # y-axis title\n  theme_classic() +                                  # specify theme\n  theme(legend.position = \"bottom\")                  # legend position \n```\n\n::: {.cell-output-display}\n![](C04_analyze_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n:::\n\nAlternatively, we could create a bar plot where the height is scaled relative to the mean. This also allows us to add error bars that are scaled to the length of the standard deviation[^c04_analyze-4]. Bar plots take up a lot of \"ink\" and so an alternative is to create a plot using a point range. In that case the mean is represented by a point and the standard deviation by lines extending out from that point.\n\n[^c04_analyze-4]: This is a classic plot for experiments with multiple treatments\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# plot mean and standard deviation\nsummary <- length_ex %>%\n  group_by(deicer, treatment_level) %>%\n  summarise(mean = mean(length_mm),\n            sd = sd(length_mm))\n\nggplot(summary) +\n  geom_pointrange(aes(x = treatment_level,\n                      y = mean,\n                      ymin = mean-sd,\n                      ymax = mean+sd,\n                      color = treatment_level),\n                  size = 1.2) +\n  facet_grid(. ~ deicer, scales = \"free_x\") +\n  scale_color_manual(values = c(\"#4E5283\", \n                               \"#7871AA\", \n                               \"#D9BBF9\",\n                               \"#AA9FB1\")) +\n  labs(x = \"deicer treatment\",\n       y = \"seedling length [mm]\") +\n  theme_bw() +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![Mean seedling length and standard deviation after 1 week for radish seeds explosed to deicers at various treatment levels.](C04_analyze_files/figure-html/fig-length-bar-1.png){#fig-length-bar width=672}\n:::\n:::\n\n\n::: {.callout-tip title=\"Give it a try\"}\nModify the code above to produce a plot for your data set.\n:::\n\n::: {.callout-note title=\"Answer\" collapse=\"true\"}\nSection A\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# plot mean and standard deviation\nsummary <- length_A %>%\n  group_by(deicer, treatment_level) %>%\n  summarise(mean = mean(length_mm),\n            sd = sd(length_mm))\n\nggplot(summary) +\n  geom_pointrange(aes(x = treatment_level,\n                      y = mean,\n                      ymin = mean-sd,\n                      ymax = mean+sd,\n                      color = treatment_level),\n                  size = 1.2) +\n  facet_grid(. ~ deicer, scales = \"free_x\") +\n  scale_color_manual(values = c(\"#4E5283\", \n                               \"#7871AA\", \n                               \"#D9BBF9\",\n                               \"#AA9FB1\")) +\n  labs(x = \"better x-axis title\",\n       y = \"better y-axis title\") +\n  theme_bw() +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](C04_analyze_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\nSection B\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# plot mean and standard deviation\nsummary <- length_B %>%\n  group_by(deicer, treatment_level) %>%\n  summarise(mean = mean(length_mm),\n            sd = sd(length_mm))\n\nggplot(summary) +\n  geom_pointrange(aes(x = treatment_level,\n                      y = mean,\n                      ymin = mean-sd,\n                      ymax = mean+sd,\n                      color = treatment_level),\n                  size = 1.2) +\n  facet_grid(. ~ deicer, scales = \"free_x\") +\n  scale_color_manual(values = c(\"#4E5283\", \n                               \"#7871AA\", \n                               \"#D9BBF9\",\n                               \"#AA9FB1\")) +\n  labs(x = \"better x-axis title\",\n       y = \"better y-axis title\") +\n  theme_bw() +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](C04_analyze_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n:::\n\n::: {.callout-tip title=\"Give it a try\"}\nDescribe your results. Make sure that you are being specific and adding context to make it easy for your reader to identify the key patterns. Consider this thinking out loud in a way where you have a set of notes that you can then edit for your report.\n\nAs rule of thumb, you should describe your results so that your reader has all the key information they need even without seeing the data tables. Make sure that you describe broad patterns before you report notable highlights. As you work through your description, interpretation, and discussion you may need to come back to your original description and revise it because you'll have a better idea of what your discussion will look like and which highlights you want to mention here so that you can pick up on them again at a later point.\n\nRemember, at this point you should not be interpreting your results!\n:::\n\n::: {.callout-note title=\"Answer\" collapse=\"true\"}\nYour description could look something like this:\n\nBroad pattern:\n\n> Overall, seedling growth was lower for radish seeds exposed to deicer X compared to the control.\n\nDetails\n\n> Mean seedling growth after 1 week was xx +/- xx mm for plants exposed to deicer X compared to a mean length of yyy +/- yy mm in the control. Similarly, the variability in seedling length was higher in exposed radish seeds (range = zz -zz mm) compared to the control (range = zz- zz mm).\n\nIn this case, you would not need to include table because you've included all the values, rather you might chose to include figure that effectively summarizes your data that you would then reference here.\n\nHere are some examples for our mung bean data set.\n\n**Emphasis on \"Broad Patterns First, Then Notable Highlights\" pattern of description**\n\nOverall, seedling length varied across treatments, with higher deicer concentrations generally leading to shorter seedlings. The control group had the longest seedlings, with a mean of 11.2 cm. In contrast, the highest concentrations of commercial blend and rock salt resulted in the shortest seedlings, with means of 3.7 cm and 4.0 cm, respectively.\n\nAmong the cheese brine treatments, seedlings in the high concentration group were shorter (mean = 7.6 cm) compared to the medium (10.4 cm) and low (10.5 cm) treatments, which were similar to the control. A similar trend was observed in the commercial blend and rock salt treatments, where seedlings were substantially shorter at high concentrations but increased in length at medium and low levels. For example, rock salt at high concentration resulted in a mean seedling length of 4.0 cm, but at medium concentration, the mean increased to 6.4 cm, and at low concentration, seedlings were comparable to the control (10.5 cm).\n\n**Emphasis on \"Describing Patterns with Context and Comparisons\"**\n\nThe data indicate that high concentrations of all deicers negatively impacted seedling growth, while lower concentrations had less effect. Seedlings in the control treatment had the greatest median length (11.5 cm), while the shortest seedlings were observed in the high concentration commercial blend (median = 3.5 cm) and rock salt (median = 3.5 cm) treatments.\n\nThe cheese brine treatment followed a dose-dependent trend, where seedlings in the high concentration group were notably shorter (mean = 7.6 cm) compared to those in the medium and low concentration groups (10.4 cm and 10.5 cm, respectively). The commercial blend also followed this pattern, though the effect was more pronounced, with the high concentration reducing seedling length to 3.7 cm on average.\n\nRock salt had a similar negative effect at high concentrations (mean = 4.0 cm) but showed some recovery at medium concentration (6.4 cm) and full recovery at low concentration, where the mean length (10.5 cm) was nearly identical to the control.\n\n**Emphasis on \"Notable Findings\"**\n\nSeedling growth was strongly affected by deicer type and concentration. Notably, the highest concentrations of commercial blend and rock salt had the most severe impact, reducing mean seedling length to 3.7 cm and 4.0 cm, respectively. In contrast, cheese brine had a less pronounced effect, with the high concentration resulting in a mean length of 7.6 cm.\n\nInterestingly, at low concentrations, seedlings exposed to all deicers had lengths comparable to the control (10.5–10.6 cm vs. 11.2 cm in the control), suggesting that at lower doses, deicers may not significantly inhibit growth. However, at medium and high concentrations, all treatments except cheese brine caused substantial reductions in seedling length.\n:::\n\nAgain, our set of summary statistics and data visualization enable us to present the patterns in our data set. However, at this point we cannot make statement whether our observed differences in seedling lengths are within the range of variability in growth we would expect to see even if the deicer does not have an effect on growth.\n\n### Test for significance\n\nFor a pairwise comparison between two means we would apply a $t$-test to evaluate the difference between means. However in this case we have multiple treatments that we want to compare and so we would use an ANOVA (analysis of variance). Similar to our germination data that will only tell us if there is significant variance in the data set overall and we will need to follow this with pairwise comparisons.\n\n#### Step 3: State your your null and alternate hypothesis and predict the outcome assuming the null hypothesis is true.\n\n::: {.callout-tip title=\"Give it a try\"}\nState your null and alternative hypothesis and predict the outcome if each claim is true.\n:::\n\n::: {.callout-note title=\"Answer\" collapse=\"true\"}\nYour null hypothesis is a claim that there is no effect:\n\n-   $H_{0}$: Presence of deicers does not have an effect on the growth rate of radish seeds.\n-   Prediction: The seedling length does not differ between the experimental treatments.\n\nThe alternative hypothesis is a claim that there is an observed effect.\n\n-   $H_{0}$: Presence of deicers has a negative effect on the growth rate of radish seeds.\n-   Prediction: The seedling length for seeds exposed to plant X will be lower compared to the control.\n:::\n\n#### Step 4: Specify a significance threshold.\n\n::: {.callout-tip title=\"Consider this\"}\nWe will specify our significance threshold $\\alpha$ as 0.05.\n\nExplain what this means and why it is important for us to specify this.\n:::\n\n::: {.callout-note title=\"Answer\" collapse=\"true\"}\nThis means that if our observed results have a less than 5% probability occurring according to our null distribution we will reject our null hypothesis.\n:::\n\n#### Step 5: Calculate your test statistic and generate sampling distribution and Step 6: Get your p-value.\n\nLet's perform the analysis of variance. To do this we need to specify the columns containing dependent variable and the independent variable using a \"formula notation\" (column names separated by a `~` ) as well as the object containing our data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Perform ANOVA\nanova_ex <- aov(length_mm ~ treatment, data = length_ex)\n\n# View summary of ANOVA results\nsummary(anova_ex)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n             Df Sum Sq Mean Sq F value Pr(>F)    \ntreatment     9   2269  252.13   43.24 <2e-16 ***\nResiduals   430   2507    5.83                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\n**Interpreting the ANOVA Output**\n\n-   **\"Df\" (Degrees of Freedom):** Shows how many groups and observations are in the analysis.\n-   **\"Sum Sq\" (Sum of Squares):** Measures total variation in the data.\n-   **\"Mean Sq\" (Mean Square):** Sum of squares divided by degrees of freedom.\n-   **\"F value\":** The test statistic; higher values indicate greater differences between groups.\n-   **\"Pr(\\>F)\" (p-value):** If **p \\< 0.05**, we reject the null hypothesis and conclude that at least one treatment level has a significantly different mean.\n\n::: {.callout-tip title=\"Give it a try\"}\nModify the code above to perform an ANOVA on your data set.\n:::\n\n::: {.callout-note title=\"Answer\" collapse=\"true\"}\nSection A:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Perform ANOVA\nanova_A <- aov(length_mm ~ treatment, data = length_A)\n\n# View summary of ANOVA results\nsummary(anova_A)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n             Df Sum Sq Mean Sq F value Pr(>F)    \ntreatment     8  94773   11847   26.09 <2e-16 ***\nResiduals   526 238859     454                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\nSection B:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Perform ANOVA\nanova_B <- aov(length_mm ~ treatment, data = length_B)\n\n# View summary of ANOVA results\nsummary(anova_B)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n             Df Sum Sq Mean Sq F value Pr(>F)    \ntreatment    10 157334   15733   84.49 <2e-16 ***\nResiduals   642 119550     186                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n:::\n\nAs our p-values are below the specified threshold level of 0.05 we now know that at least one treatment has a significantly different mean. Next, we will perform post-hoc Tukey tests so that we can determine which pairwise comparisons are significant. If a pairwise comparison has **p \\< 0.05**, those two treatment levels have a statistically significant difference in seedling length. This approach allows us to determine whether deicer type and treatment level influences seedling length and, if so, which specific treatments cause the differences.\n\nAgain we will then filter our output so that we have a much smaller table that only shows pairs that are significantly different.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Post-hoc test to compare treatment levels\ntukey_df <- tidy(TukeyHSD(anova_ex))\n\n# look at first few rows\ntukey_df %>%\n  head() %>%\n  kable()\n```\n\n::: {.cell-output-display}\n|term      |contrast                              | null.value|   estimate|  conf.low| conf.high| adj.p.value|\n|:---------|:-------------------------------------|----------:|----------:|---------:|---------:|-----------:|\n|treatment |cheese_brine_low-cheese_brine_high    |          0|  2.9186667|  1.090479|  4.746855|   0.0000250|\n|treatment |cheese_brine_medium-cheese_brine_high |          0|  2.8376667|  1.009479|  4.665855|   0.0000497|\n|treatment |comm_blend_high-cheese_brine_high     |          0| -3.9396667| -6.019400| -1.859933|   0.0000002|\n|treatment |comm_blend_low-cheese_brine_high      |          0|  3.0203333|  1.192145|  4.848521|   0.0000103|\n|treatment |comm_blend_medium-cheese_brine_high   |          0|  0.8312195| -1.117580|  2.780019|   0.9394135|\n|treatment |control_NA-cheese_brine_high          |          0|  3.5996667|  1.771479|  5.427855|   0.0000000|\n:::\n\n```{.r .cell-code}\n# print table with significant pairwise comparisons\ntukey_df %>%\n  filter(adj.p.value <= 0.05) %>%\n  kable()\n```\n\n::: {.cell-output-display}\n|term      |contrast                              | null.value|  estimate|   conf.low|  conf.high| adj.p.value|\n|:---------|:-------------------------------------|----------:|---------:|----------:|----------:|-----------:|\n|treatment |cheese_brine_low-cheese_brine_high    |          0|  2.918667|  1.0904786|  4.7468547|   0.0000250|\n|treatment |cheese_brine_medium-cheese_brine_high |          0|  2.837667|  1.0094786|  4.6658547|   0.0000497|\n|treatment |comm_blend_high-cheese_brine_high     |          0| -3.939667| -6.0194004| -1.8599329|   0.0000002|\n|treatment |comm_blend_low-cheese_brine_high      |          0|  3.020333|  1.1921453|  4.8485214|   0.0000103|\n|treatment |control_NA-cheese_brine_high          |          0|  3.599667|  1.7714786|  5.4278547|   0.0000000|\n|treatment |rock_salt_high-cheese_brine_high      |          0| -3.585385| -6.2114598| -0.9593095|   0.0007334|\n|treatment |rock_salt_low-cheese_brine_high       |          0|  2.944667|  1.1164786|  4.7728547|   0.0000200|\n|treatment |comm_blend_high-cheese_brine_low      |          0| -6.858333| -8.5756170| -5.1410497|   0.0000000|\n|treatment |comm_blend_medium-cheese_brine_low    |          0| -2.087447| -3.6435925| -0.5313018|   0.0010100|\n|treatment |rock_salt_high-cheese_brine_low       |          0| -6.504051| -8.8535281| -4.1545745|   0.0000000|\n|treatment |rock_salt_medium-cheese_brine_low     |          0| -4.158022| -5.8567394| -2.4593036|   0.0000000|\n|treatment |comm_blend_high-cheese_brine_medium   |          0| -6.777333| -8.4946170| -5.0600497|   0.0000000|\n|treatment |comm_blend_medium-cheese_brine_medium |          0| -2.006447| -3.5625925| -0.4503018|   0.0019891|\n|treatment |rock_salt_high-cheese_brine_medium    |          0| -6.423051| -8.7725281| -4.0735745|   0.0000000|\n|treatment |rock_salt_medium-cheese_brine_medium  |          0| -4.077021| -5.7757394| -2.3783036|   0.0000000|\n|treatment |comm_blend_low-comm_blend_high        |          0|  6.960000|  5.2427164|  8.6772836|   0.0000000|\n|treatment |comm_blend_medium-comm_blend_high     |          0|  4.770886|  2.9257278|  6.6160446|   0.0000000|\n|treatment |control_NA-comm_blend_high            |          0|  7.539333|  5.8220497|  9.2566170|   0.0000000|\n|treatment |rock_salt_low-comm_blend_high         |          0|  6.884333|  5.1670497|  8.6016170|   0.0000000|\n|treatment |rock_salt_medium-comm_blend_high      |          0|  2.700312|  0.7334200|  4.6672037|   0.0006617|\n|treatment |comm_blend_medium-comm_blend_low      |          0| -2.189114| -3.7452592| -0.6329684|   0.0004152|\n|treatment |rock_salt_high-comm_blend_low         |          0| -6.605718| -8.9551947| -4.2562411|   0.0000000|\n|treatment |rock_salt_medium-comm_blend_low       |          0| -4.259688| -5.9584060| -2.5609703|   0.0000000|\n|treatment |control_NA-comm_blend_medium          |          0|  2.768447|  1.2123018|  4.3245925|   0.0000012|\n|treatment |rock_salt_high-comm_blend_medium      |          0| -4.416604| -6.8611056| -1.9721026|   0.0000008|\n|treatment |rock_salt_low-comm_blend_medium       |          0|  2.113447|  0.5573018|  3.6695925|   0.0008079|\n|treatment |rock_salt_medium-comm_blend_medium    |          0| -2.070574| -3.8984662| -0.2426825|   0.0128487|\n|treatment |rock_salt_high-control_NA             |          0| -7.185051| -9.5345281| -4.8355745|   0.0000000|\n|treatment |rock_salt_medium-control_NA           |          0| -4.839022| -6.5377394| -3.1403036|   0.0000000|\n|treatment |rock_salt_low-rock_salt_high          |          0|  6.530051|  4.1805745|  8.8795281|   0.0000000|\n|treatment |rock_salt_medium-rock_salt_low        |          0| -4.184022| -5.8827394| -2.4853036|   0.0000000|\n:::\n\n```{.r .cell-code}\n# print table with pairwise comparisons that are not significantly different\ntukey_df %>%\n  filter(adj.p.value >= 0.05) %>%\n  kable()\n```\n\n::: {.cell-output-display}\n|term      |contrast                             | null.value|   estimate|   conf.low| conf.high| adj.p.value|\n|:---------|:------------------------------------|----------:|----------:|----------:|---------:|-----------:|\n|treatment |comm_blend_medium-cheese_brine_high  |          0|  0.8312195| -1.1175796| 2.7800186|   0.9394135|\n|treatment |rock_salt_medium-cheese_brine_high   |          0| -1.2393548| -3.3037850| 0.8250753|   0.6627416|\n|treatment |cheese_brine_medium-cheese_brine_low |          0| -0.0810000| -1.4831562| 1.3211562|   1.0000000|\n|treatment |comm_blend_low-cheese_brine_low      |          0|  0.1016667| -1.3004896| 1.5038229|   1.0000000|\n|treatment |control_NA-cheese_brine_low          |          0|  0.6810000| -0.7211562| 2.0831562|   0.8732405|\n|treatment |rock_salt_low-cheese_brine_low       |          0|  0.0260000| -1.3761562| 1.4281562|   1.0000000|\n|treatment |comm_blend_low-cheese_brine_medium   |          0|  0.1826667| -1.2194896| 1.5848229|   0.9999942|\n|treatment |control_NA-cheese_brine_medium       |          0|  0.7620000| -0.6401562| 2.1641562|   0.7787748|\n|treatment |rock_salt_low-cheese_brine_medium    |          0|  0.1070000| -1.2951562| 1.5091562|   0.9999999|\n|treatment |rock_salt_high-comm_blend_high       |          0|  0.3542821| -2.1958282| 2.9043923|   0.9999898|\n|treatment |control_NA-comm_blend_low            |          0|  0.5793333| -0.8228229| 1.9814896|   0.9501285|\n|treatment |rock_salt_low-comm_blend_low         |          0| -0.0756667| -1.4778229| 1.3264896|   1.0000000|\n|treatment |rock_salt_low-control_NA             |          0| -0.6550000| -2.0571562| 0.7471562|   0.8973800|\n|treatment |rock_salt_medium-rock_salt_high      |          0|  2.3460298| -0.1916151| 4.8836747|   0.0978707|\n:::\n:::\n\n\n::: {.callout-tip title=\"Give it a try\"}\nModify the code above to run pairwise Tukey Tests on your data set.\n:::\n\n::: {.callout-note title=\"Answer\" collapse=\"true\"}\nSection A\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Post-hoc test to compare treatment levels\ntukey_df <- tidy(TukeyHSD(anova_A))\n\n# look at first few rows\ntukey_df %>%\n  head() %>%\n  kable()\n```\n\n::: {.cell-output-display}\n|term      |contrast                     | null.value|    estimate|  conf.low|  conf.high| adj.p.value|\n|:---------|:----------------------------|----------:|-----------:|---------:|----------:|-----------:|\n|treatment |Fusion2330_high-control_NA   |          0|  -6.6793785| -18.84890|   5.490143|   0.7405609|\n|treatment |Fusion2330_low-control_NA    |          0|   6.8206215|  -5.34890|  18.990143|   0.7177506|\n|treatment |Fusion2330_medium-control_NA |          0|  -0.0558153| -12.32892|  12.217293|   1.0000000|\n|treatment |Fusion2330_trace-control_NA  |          0|   0.1372881| -12.03223|  12.306809|   1.0000000|\n|treatment |NaCl_high-control_NA         |          0| -37.5593220| -49.77987| -25.338775|   0.0000000|\n|treatment |NaCl_low-control_NA          |          0|  -3.6949153| -15.91546|   8.525631|   0.9904291|\n:::\n\n```{.r .cell-code}\n# print table with significant pairwise comparisons\ntukey_df %>%\n  filter(adj.p.value <= 0.05) %>%\n  kable()\n```\n\n::: {.cell-output-display}\n|term      |contrast                       | null.value|  estimate|    conf.low|   conf.high| adj.p.value|\n|:---------|:------------------------------|----------:|---------:|-----------:|-----------:|-----------:|\n|treatment |NaCl_high-control_NA           |          0| -37.55932| -49.7798687| -25.3387754|   0.0000000|\n|treatment |NaCl_trace-control_NA          |          0|  13.23729|   1.0677669|  25.4068093|   0.0214244|\n|treatment |Fusion2330_low-Fusion2330_high |          0|  13.50000|   1.3817191|  25.6182809|   0.0163301|\n|treatment |NaCl_high-Fusion2330_high      |          0| -30.87994| -43.0494647| -18.7104223|   0.0000000|\n|treatment |NaCl_trace-Fusion2330_high     |          0|  19.91667|   7.7983858|  32.0349475|   0.0000152|\n|treatment |NaCl_high-Fusion2330_low       |          0| -44.37994| -56.5494647| -32.2104223|   0.0000000|\n|treatment |NaCl_medium-Fusion2330_low     |          0| -12.70000| -24.8182809|  -0.5817191|   0.0318113|\n|treatment |NaCl_high-Fusion2330_medium    |          0| -37.50351| -49.7766151| -25.2303983|   0.0000000|\n|treatment |NaCl_trace-Fusion2330_medium   |          0|  13.29310|   1.0708011|  25.5154058|   0.0214529|\n|treatment |NaCl_high-Fusion2330_trace     |          0| -37.69661| -49.8661314| -25.5270890|   0.0000000|\n|treatment |NaCl_trace-Fusion2330_trace    |          0|  13.10000|   0.9817191|  25.2182809|   0.0229377|\n|treatment |NaCl_low-NaCl_high             |          0|  33.86441|  21.6438601|  46.0849534|   0.0000000|\n|treatment |NaCl_medium-NaCl_high          |          0|  31.67994|  19.5104223|  43.8494647|   0.0000000|\n|treatment |NaCl_trace-NaCl_high           |          0|  50.79661|  38.6270890|  62.9661314|   0.0000000|\n|treatment |NaCl_trace-NaCl_low            |          0|  16.93220|   4.7626822|  29.1017246|   0.0005913|\n|treatment |NaCl_trace-NaCl_medium         |          0|  19.11667|   6.9983858|  31.2349475|   0.0000419|\n:::\n\n```{.r .cell-code}\n# print table with pairwise comparisons that are not significantly different\ntukey_df %>%\n  filter(adj.p.value >= 0.05) %>%\n  kable()\n```\n\n::: {.cell-output-display}\n|term      |contrast                           | null.value|    estimate|   conf.low| conf.high| adj.p.value|\n|:---------|:----------------------------------|----------:|-----------:|----------:|---------:|-----------:|\n|treatment |Fusion2330_high-control_NA         |          0|  -6.6793785| -18.848900|  5.490143|   0.7405609|\n|treatment |Fusion2330_low-control_NA          |          0|   6.8206215|  -5.348900| 18.990143|   0.7177506|\n|treatment |Fusion2330_medium-control_NA       |          0|  -0.0558153| -12.328924| 12.217293|   1.0000000|\n|treatment |Fusion2330_trace-control_NA        |          0|   0.1372881| -12.032233| 12.306809|   1.0000000|\n|treatment |NaCl_low-control_NA                |          0|  -3.6949153| -15.915462|  8.525631|   0.9904291|\n|treatment |NaCl_medium-control_NA             |          0|  -5.8793785| -18.048900|  6.290143|   0.8531762|\n|treatment |Fusion2330_medium-Fusion2330_high  |          0|   6.6235632|  -5.598739| 18.845866|   0.7538361|\n|treatment |Fusion2330_trace-Fusion2330_high   |          0|   6.8166667|  -5.301614| 18.934947|   0.7136622|\n|treatment |NaCl_low-Fusion2330_high           |          0|   2.9844633|  -9.185058| 15.153984|   0.9977243|\n|treatment |NaCl_medium-Fusion2330_high        |          0|   0.8000000| -11.318281| 12.918281|   0.9999999|\n|treatment |Fusion2330_medium-Fusion2330_low   |          0|  -6.8764368| -19.098739|  5.345866|   0.7134559|\n|treatment |Fusion2330_trace-Fusion2330_low    |          0|  -6.6833333| -18.801614|  5.434947|   0.7354223|\n|treatment |NaCl_low-Fusion2330_low            |          0| -10.5155367| -22.685058|  1.653984|   0.1533328|\n|treatment |NaCl_trace-Fusion2330_low          |          0|   6.4166667|  -5.701614| 18.534948|   0.7768701|\n|treatment |Fusion2330_trace-Fusion2330_medium |          0|   0.1931034| -12.029199| 12.415406|   1.0000000|\n|treatment |NaCl_low-Fusion2330_medium         |          0|  -3.6390999| -15.912208|  8.634009|   0.9915932|\n|treatment |NaCl_medium-Fusion2330_medium      |          0|  -5.8235632| -18.045866|  6.398739|   0.8627324|\n|treatment |NaCl_low-Fusion2330_trace          |          0|  -3.8322034| -16.001725|  8.337318|   0.9874989|\n|treatment |NaCl_medium-Fusion2330_trace       |          0|  -6.0166667| -18.134947|  6.101614|   0.8328730|\n|treatment |NaCl_medium-NaCl_low               |          0|  -2.1844633| -14.353984|  9.985058|   0.9997671|\n:::\n:::\n\n\nSection B\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Post-hoc test to compare treatment levels\ntukey_df <- tidy(TukeyHSD(anova_A))\n\n# look at first few rows\ntukey_df %>%\n  head() %>%\n  kable()\n```\n\n::: {.cell-output-display}\n|term      |contrast                     | null.value|    estimate|  conf.low|  conf.high| adj.p.value|\n|:---------|:----------------------------|----------:|-----------:|---------:|----------:|-----------:|\n|treatment |Fusion2330_high-control_NA   |          0|  -6.6793785| -18.84890|   5.490143|   0.7405609|\n|treatment |Fusion2330_low-control_NA    |          0|   6.8206215|  -5.34890|  18.990143|   0.7177506|\n|treatment |Fusion2330_medium-control_NA |          0|  -0.0558153| -12.32892|  12.217293|   1.0000000|\n|treatment |Fusion2330_trace-control_NA  |          0|   0.1372881| -12.03223|  12.306809|   1.0000000|\n|treatment |NaCl_high-control_NA         |          0| -37.5593220| -49.77987| -25.338775|   0.0000000|\n|treatment |NaCl_low-control_NA          |          0|  -3.6949153| -15.91546|   8.525631|   0.9904291|\n:::\n\n```{.r .cell-code}\n# print table with significant pairwise comparisons\ntukey_df %>%\n  filter(adj.p.value <= 0.05) %>%\n  kable()\n```\n\n::: {.cell-output-display}\n|term      |contrast                       | null.value|  estimate|    conf.low|   conf.high| adj.p.value|\n|:---------|:------------------------------|----------:|---------:|-----------:|-----------:|-----------:|\n|treatment |NaCl_high-control_NA           |          0| -37.55932| -49.7798687| -25.3387754|   0.0000000|\n|treatment |NaCl_trace-control_NA          |          0|  13.23729|   1.0677669|  25.4068093|   0.0214244|\n|treatment |Fusion2330_low-Fusion2330_high |          0|  13.50000|   1.3817191|  25.6182809|   0.0163301|\n|treatment |NaCl_high-Fusion2330_high      |          0| -30.87994| -43.0494647| -18.7104223|   0.0000000|\n|treatment |NaCl_trace-Fusion2330_high     |          0|  19.91667|   7.7983858|  32.0349475|   0.0000152|\n|treatment |NaCl_high-Fusion2330_low       |          0| -44.37994| -56.5494647| -32.2104223|   0.0000000|\n|treatment |NaCl_medium-Fusion2330_low     |          0| -12.70000| -24.8182809|  -0.5817191|   0.0318113|\n|treatment |NaCl_high-Fusion2330_medium    |          0| -37.50351| -49.7766151| -25.2303983|   0.0000000|\n|treatment |NaCl_trace-Fusion2330_medium   |          0|  13.29310|   1.0708011|  25.5154058|   0.0214529|\n|treatment |NaCl_high-Fusion2330_trace     |          0| -37.69661| -49.8661314| -25.5270890|   0.0000000|\n|treatment |NaCl_trace-Fusion2330_trace    |          0|  13.10000|   0.9817191|  25.2182809|   0.0229377|\n|treatment |NaCl_low-NaCl_high             |          0|  33.86441|  21.6438601|  46.0849534|   0.0000000|\n|treatment |NaCl_medium-NaCl_high          |          0|  31.67994|  19.5104223|  43.8494647|   0.0000000|\n|treatment |NaCl_trace-NaCl_high           |          0|  50.79661|  38.6270890|  62.9661314|   0.0000000|\n|treatment |NaCl_trace-NaCl_low            |          0|  16.93220|   4.7626822|  29.1017246|   0.0005913|\n|treatment |NaCl_trace-NaCl_medium         |          0|  19.11667|   6.9983858|  31.2349475|   0.0000419|\n:::\n\n```{.r .cell-code}\n# print table with pairwise comparisons that are not significantly different\ntukey_df %>%\n  filter(adj.p.value >= 0.05) %>%\n  kable()\n```\n\n::: {.cell-output-display}\n|term      |contrast                           | null.value|    estimate|   conf.low| conf.high| adj.p.value|\n|:---------|:----------------------------------|----------:|-----------:|----------:|---------:|-----------:|\n|treatment |Fusion2330_high-control_NA         |          0|  -6.6793785| -18.848900|  5.490143|   0.7405609|\n|treatment |Fusion2330_low-control_NA          |          0|   6.8206215|  -5.348900| 18.990143|   0.7177506|\n|treatment |Fusion2330_medium-control_NA       |          0|  -0.0558153| -12.328924| 12.217293|   1.0000000|\n|treatment |Fusion2330_trace-control_NA        |          0|   0.1372881| -12.032233| 12.306809|   1.0000000|\n|treatment |NaCl_low-control_NA                |          0|  -3.6949153| -15.915462|  8.525631|   0.9904291|\n|treatment |NaCl_medium-control_NA             |          0|  -5.8793785| -18.048900|  6.290143|   0.8531762|\n|treatment |Fusion2330_medium-Fusion2330_high  |          0|   6.6235632|  -5.598739| 18.845866|   0.7538361|\n|treatment |Fusion2330_trace-Fusion2330_high   |          0|   6.8166667|  -5.301614| 18.934947|   0.7136622|\n|treatment |NaCl_low-Fusion2330_high           |          0|   2.9844633|  -9.185058| 15.153984|   0.9977243|\n|treatment |NaCl_medium-Fusion2330_high        |          0|   0.8000000| -11.318281| 12.918281|   0.9999999|\n|treatment |Fusion2330_medium-Fusion2330_low   |          0|  -6.8764368| -19.098739|  5.345866|   0.7134559|\n|treatment |Fusion2330_trace-Fusion2330_low    |          0|  -6.6833333| -18.801614|  5.434947|   0.7354223|\n|treatment |NaCl_low-Fusion2330_low            |          0| -10.5155367| -22.685058|  1.653984|   0.1533328|\n|treatment |NaCl_trace-Fusion2330_low          |          0|   6.4166667|  -5.701614| 18.534948|   0.7768701|\n|treatment |Fusion2330_trace-Fusion2330_medium |          0|   0.1931034| -12.029199| 12.415406|   1.0000000|\n|treatment |NaCl_low-Fusion2330_medium         |          0|  -3.6390999| -15.912208|  8.634009|   0.9915932|\n|treatment |NaCl_medium-Fusion2330_medium      |          0|  -5.8235632| -18.045866|  6.398739|   0.8627324|\n|treatment |NaCl_low-Fusion2330_trace          |          0|  -3.8322034| -16.001725|  8.337318|   0.9874989|\n|treatment |NaCl_medium-Fusion2330_trace       |          0|  -6.0166667| -18.134947|  6.101614|   0.8328730|\n|treatment |NaCl_medium-NaCl_low               |          0|  -2.1844633| -14.353984|  9.985058|   0.9997671|\n:::\n:::\n\n:::\n\n#### Step 7: Interpret the results and draw conclusions.\n\n::: {.callout-tip title=\"Give it a try\"}\nCompare your p-value to the threshold of significance we defined above to determine how to interpret the results of your ANOVA and Tukey post-hoc tests.\n\nThen update the results you formulated earlier to add this information into your description of the results.\n:::\n\n::: {.callout-note title=\"Answer\" collapse=\"true\"}\nHere's an example of a description of results including ANOVA and Tukey Test Results.\n\nOverall, seedling length varied across treatments, with higher deicer concentrations generally leading to shorter seedlings (ANOVA, p \\< 0.05). The control group had the longest seedlings (mean = 11.2 cm), while the highest concentrations of commercial blend and rock salt resulted in the shortest seedlings (means = 3.7 cm and 4.0 cm, respectively). Tukey post-hoc tests confirmed that these reductions were statistically significant compared to the control (p \\< 0.0001).\n\nAmong the cheese brine treatments, seedlings in the high concentration group were significantly shorter (mean = 7.6 cm) than those in the medium (10.4 cm, p = 0.002) and low (10.5 cm, p = 0.001) treatments, which were not significantly different from the control. A similar trend was observed for commercial blend and rock salt treatments, where high concentrations resulted in significant reductions (p \\< 0.0001), but seedling length increased at medium and low levels. For example, rock salt at high concentration led to a mean seedling length of 4.0 cm, but at medium concentration, the mean increased to 6.4 cm (p = 0.008), and at low concentration, seedlings were comparable to the control (10.5 cm, p = 0.45, not significant).\n\nThese results suggest a dose-dependent effect, where high concentrations of all deicers significantly inhibited growth, while lower concentrations had a reduced or negligible impact. Notably, cheese brine had a less severe effect compared to commercial blend and rock salt, as seedlings at high concentration were still significantly longer than those in the commercial blend high and rock salt high treatments (p = 0.0002 and p = 0.0005, respectively).\n:::\n\nRemember, if your results are not statistically significant, you still need to write a set of conclusions! Even though we seem to think that \"negative results\" are \"bad\", \"negative\" just means that we did not observe an effect - but that is also a result because you can now exclude one possible explanation for your observation and move on to test the next one.\n",
    "supporting": [
      "C04_analyze_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}